import { WardInfo, ProtectionPoint, HealthcareFacility } from './types.js';

// Haversine formula to compute great-circle distance in kilometers
export function calculateDistanceKm(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 6371; // Earth's radius in km
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLon = ((lon2 - lon1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLon / 2) *
      Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return Math.round(R * c * 10) / 10;
}

// Ray-casting point in polygon
export function pointInPolygon(point: [number, number], vs: [number, number][]): boolean {
  const x = point[0];
  const y = point[1];
  let inside = false;
  for (let i = 0, j = vs.length - 1; i < vs.length; j = i++) {
    const xi = vs[i][0];
    const yi = vs[i][1];
    const xj = vs[j][0];
    const yj = vs[j][1];
    const intersect = yi > y !== yj > y && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi;
    if (intersect) inside = !inside;
  }
  return inside;
}

// ==============================================================================
// 1. MAHARASHTRA STATEWIDE WARDS & MUNICIPAL DIVISIONS
// ==============================================================================
export const MAHARASHTRA_WARDS: WardInfo[] = [
  // --- Pune Municipal Corporation (PMC) ---
  {
    id: 'ward-14',
    name: 'Ward 14: Shivajinagar - Ghole Road, Pune',
    zone: 'Central Pune Zone',
    city: 'Pune',
    state: 'Maharashtra',
    regionType: 'Maharashtra',
    center: [18.5314, 73.8446],
    bounds: [
      [18.542, 73.834],
      [18.545, 73.856],
      [18.524, 73.861],
      [18.518, 73.839],
      [18.542, 73.834],
    ],
    population: 142000,
    vulnerableCount: 28400,
    treeCanopyPct: 32,
    builtDensityPct: 68,
    vulnerabilityIndex: 58,
    uhiOffsetDegC: 1.8,
    highRiskAreas: ['FC Road Shopping Spine', 'Shivajinagar Bus & Railway Terminus', 'Modern College Square'],
    lowRiskAreas: ['Sambhaji Park Canopy', 'Agricultural College Green Belt', 'Mutha River Greenway'],
  },
  {
    id: 'ward-21',
    name: 'Ward 21: Kasba Peth - Vishrambaug Wada, Pune',
    zone: 'Heritage Core Zone',
    city: 'Pune',
    state: 'Maharashtra',
    regionType: 'Maharashtra',
    center: [18.5178, 73.8582],
    bounds: [
      [18.526, 73.851],
      [18.528, 73.866],
      [18.511, 73.869],
      [18.508, 73.852],
      [18.526, 73.851],
    ],
    population: 178000,
    vulnerableCount: 46200,
    treeCanopyPct: 11,
    builtDensityPct: 89,
    vulnerabilityIndex: 84,
    uhiOffsetDegC: 3.2,
    highRiskAreas: ['Mandai Wholesale Bazaar', 'Laxmi Road Dense Corridor', 'Phadke Haud Transit'],
    lowRiskAreas: ['Shaniwar Wada Shaded Lawns', 'PMC Saraswati High School Covered Quad'],
  },
  {
    id: 'ward-09',
    name: 'Ward 9: Kothrud - Bavdhan, Pune',
    zone: 'West Hills Zone',
    city: 'Pune',
    state: 'Maharashtra',
    regionType: 'Maharashtra',
    center: [18.5074, 73.8077],
    bounds: [
      [18.521, 73.792],
      [18.523, 73.821],
      [18.491, 73.818],
      [18.489, 73.791],
      [18.521, 73.792],
    ],
    population: 195000,
    vulnerableCount: 31000,
    treeCanopyPct: 44,
    builtDensityPct: 56,
    vulnerabilityIndex: 38,
    uhiOffsetDegC: 0.9,
    highRiskAreas: ['Karve Statue Highway Crossing', 'Chandani Chowk Flyover Junction'],
    lowRiskAreas: ['ARAI Vetal Tekdi Reserve', 'Kothrud Hillside Shaded Parks', 'MIT Garden'],
  },
  {
    id: 'ward-07',
    name: 'Ward 7: Aundh - Baner, Pune',
    zone: 'North-West Tech Zone',
    city: 'Pune',
    state: 'Maharashtra',
    regionType: 'Maharashtra',
    center: [18.558, 73.807],
    bounds: [
      [18.575, 73.792],
      [18.577, 73.824],
      [18.541, 73.828],
      [18.542, 73.794],
      [18.575, 73.792],
    ],
    population: 165000,
    vulnerableCount: 24700,
    treeCanopyPct: 36,
    builtDensityPct: 62,
    vulnerabilityIndex: 42,
    uhiOffsetDegC: 1.2,
    highRiskAreas: ['Baner High Street Open Plaza', 'Aundh ITI Uncovered Intersection'],
    lowRiskAreas: ['Pashan Lake Riparian Buffer', 'University of Pune Shaded Woods', 'Sindh Society Canopy'],
  },
  {
    id: 'ward-18',
    name: 'Ward 18: Hadapsar - Mundhwa, Pune',
    zone: 'East Industrial & Logistics Zone',
    city: 'Pune',
    state: 'Maharashtra',
    regionType: 'Maharashtra',
    center: [18.502, 73.927],
    bounds: [
      [18.524, 73.905],
      [18.528, 73.952],
      [18.481, 73.955],
      [18.479, 73.907],
      [18.524, 73.905],
    ],
    population: 230000,
    vulnerableCount: 57500,
    treeCanopyPct: 16,
    builtDensityPct: 82,
    vulnerabilityIndex: 76,
    uhiOffsetDegC: 2.7,
    highRiskAreas: ['Gadital Bustling Interchange', 'Magarpatta South Outer Ring', 'Industrial Metal Yards'],
    lowRiskAreas: ['Amanora Shaded Park Perimeter', 'Gliding Centre Buffer Zone'],
  },
  {
    id: 'ward-12',
    name: 'Ward 12: Viman Nagar - Nagar Road, Pune',
    zone: 'North-East Airport Zone',
    city: 'Pune',
    state: 'Maharashtra',
    regionType: 'Maharashtra',
    center: [18.567, 73.914],
    bounds: [
      [18.584, 73.896],
      [18.586, 73.935],
      [18.552, 73.938],
      [18.551, 73.898],
      [18.584, 73.896],
    ],
    population: 154000,
    vulnerableCount: 26000,
    treeCanopyPct: 25,
    builtDensityPct: 75,
    vulnerabilityIndex: 61,
    uhiOffsetDegC: 2.1,
    highRiskAreas: ['Pune-Ahmednagar Highway Tarmac', 'Phoenix Mall Transit Drop-off'],
    lowRiskAreas: ['Joggers Park Viman Nagar', 'Symbiosis Campus Shaded Walkways'],
  },
  {
    id: 'ward-25',
    name: 'Ward 25: Swargate - Parvati, Pune',
    zone: 'South Transit Zone',
    city: 'Pune',
    state: 'Maharashtra',
    regionType: 'Maharashtra',
    center: [18.498, 73.856],
    bounds: [
      [18.511, 73.847],
      [18.513, 73.868],
      [18.484, 73.869],
      [18.482, 73.848],
      [18.511, 73.847],
    ],
    population: 188000,
    vulnerableCount: 48800,
    treeCanopyPct: 22,
    builtDensityPct: 78,
    vulnerabilityIndex: 72,
    uhiOffsetDegC: 2.4,
    highRiskAreas: ['Swargate ST Bus Terminal Square', 'Jedhe Chowk Flyover Underdeck'],
    lowRiskAreas: ['Parvati Hill Forest Reserve', 'Sarasbaug Shaded Lake Complex'],
  },
  {
    id: 'ward-pcmc-01',
    name: 'PCMC Ward 1: Pimpri - Chinchwad - Nigdi',
    zone: 'Industrial & Auto Manufacturing Hub',
    city: 'Pune / PCMC',
    state: 'Maharashtra',
    regionType: 'Maharashtra',
    center: [18.6279, 73.8131],
    bounds: [
      [18.655, 73.785],
      [18.658, 73.835],
      [18.605, 73.838],
      [18.602, 73.788],
      [18.655, 73.785],
    ],
    population: 260000,
    vulnerableCount: 65000,
    treeCanopyPct: 18,
    builtDensityPct: 82,
    vulnerabilityIndex: 70,
    uhiOffsetDegC: 2.5,
    highRiskAreas: ['Bhakti Shakti Flyover Junction', 'MIDC Bhosari Metal Sheds', 'Old Pune-Mumbai Highway Spine'],
    lowRiskAreas: ['Appu Ghar Pradhikaran Park', 'Bird Valley Lake Promenade'],
  },

  // --- Brihanmumbai Municipal Corporation (BMC / MCGM - Mumbai) ---
  {
    id: 'ward-mum-a',
    name: 'Ward A: Colaba - Fort - Nariman Point, Mumbai',
    zone: 'South Mumbai Coastal Financial Core',
    city: 'Mumbai',
    state: 'Maharashtra',
    regionType: 'Maharashtra',
    center: [18.9220, 72.8347],
    bounds: [
      [18.945, 72.818],
      [18.948, 72.845],
      [18.905, 72.842],
      [18.902, 72.815],
      [18.945, 72.818],
    ],
    population: 185000,
    vulnerableCount: 38000,
    treeCanopyPct: 24,
    builtDensityPct: 86,
    vulnerabilityIndex: 65,
    uhiOffsetDegC: 2.2,
    highRiskAreas: ['CST Terminus Forecourt', 'Colaba Causeway Retail Strip', 'Nariman Point Glass Canyon'],
    lowRiskAreas: ['Oval Maidan Shaded Lawns', 'Gateway Waterfront Breezeway'],
  },
  {
    id: 'ward-mum-c',
    name: 'Ward C: Marine Lines - Kalbadevi - Bhuleshwar, Mumbai',
    zone: 'Historic Dense Commercial Zone',
    city: 'Mumbai',
    state: 'Maharashtra',
    regionType: 'Maharashtra',
    center: [18.9482, 72.8258],
    bounds: [
      [18.960, 72.818],
      [18.962, 72.835],
      [18.938, 72.838],
      [18.936, 72.820],
      [18.960, 72.818],
    ],
    population: 215000,
    vulnerableCount: 58000,
    treeCanopyPct: 8,
    builtDensityPct: 94,
    vulnerabilityIndex: 88,
    uhiOffsetDegC: 3.4,
    highRiskAreas: ['Crawford Market Bazaars', 'Zaveri Bazaar Narrow Lanes', 'Kalbadevi Tarmac Corridor'],
    lowRiskAreas: ['Marine Drive Promenade Edge', 'Cross Maidan Covered Pavilions'],
  },
  {
    id: 'ward-mum-d',
    name: 'Ward D: Malabar Hill - Tardeo - Girgaon, Mumbai',
    zone: 'South Coastal & Residential Ridge',
    city: 'Mumbai',
    state: 'Maharashtra',
    regionType: 'Maharashtra',
    center: [18.9667, 72.8125],
    bounds: [
      [18.985, 72.795],
      [18.988, 72.825],
      [18.950, 72.822],
      [18.948, 72.798],
      [18.985, 72.795],
    ],
    population: 172000,
    vulnerableCount: 29000,
    treeCanopyPct: 38,
    builtDensityPct: 65,
    vulnerabilityIndex: 44,
    uhiOffsetDegC: 1.1,
    highRiskAreas: ['Tardeo AC Market Junction', 'Nana Chowk Multi-tier Flyover'],
    lowRiskAreas: ['Hanging Gardens Forest Canopy', 'Chowpatty Waterfront Sea Breeze'],
  },
  {
    id: 'ward-mum-gs',
    name: 'Ward G/South: Worli - Lower Parel, Mumbai',
    zone: 'Midtown Commercial & High-Rise Mill Hub',
    city: 'Mumbai',
    state: 'Maharashtra',
    regionType: 'Maharashtra',
    center: [18.9986, 72.8311],
    bounds: [
      [19.020, 72.812],
      [19.022, 72.845],
      [18.982, 72.848],
      [18.980, 72.815],
      [19.020, 72.812],
    ],
    population: 250000,
    vulnerableCount: 52000,
    treeCanopyPct: 15,
    builtDensityPct: 88,
    vulnerabilityIndex: 78,
    uhiOffsetDegC: 2.9,
    highRiskAreas: ['Lower Parel Railway Station Bridge', 'Senapati Bapat Marg Canyon', 'Curry Road Chawls'],
    lowRiskAreas: ['Worli Seaface Promenade', 'Nehru Science Centre Park'],
  },
  {
    id: 'ward-mum-gn',
    name: 'Ward G/North: Dharavi - Dadar - Mahim, Mumbai',
    zone: 'Central High-Vulnerability Microclimate',
    city: 'Mumbai',
    state: 'Maharashtra',
    regionType: 'Maharashtra',
    center: [19.0402, 72.8509],
    bounds: [
      [19.058, 72.835],
      [19.060, 72.868],
      [19.025, 72.870],
      [19.022, 72.838],
      [19.058, 72.835],
    ],
    population: 340000,
    vulnerableCount: 112000,
    treeCanopyPct: 10,
    builtDensityPct: 92,
    vulnerabilityIndex: 91,
    uhiOffsetDegC: 3.6,
    highRiskAreas: ['Dharavi 90-Feet Road Leather Workshops', 'Dadar Flower Market Interchange', 'Sion Circle Flyover'],
    lowRiskAreas: ['Shivaji Park Shaded Perimeter', 'Mahim Nature Park Mangrove Belt'],
  },
  {
    id: 'ward-mum-he',
    name: 'Ward H/East: Bandra Kurla Complex (BKC) - Santacruz, Mumbai',
    zone: 'Financial District & Transit Core',
    city: 'Mumbai',
    state: 'Maharashtra',
    regionType: 'Maharashtra',
    center: [19.0664, 72.8682],
    bounds: [
      [19.085, 72.845],
      [19.088, 72.885],
      [19.045, 72.888],
      [19.042, 72.848],
      [19.085, 72.845],
    ],
    population: 280000,
    vulnerableCount: 68000,
    treeCanopyPct: 20,
    builtDensityPct: 83,
    vulnerabilityIndex: 74,
    uhiOffsetDegC: 2.8,
    highRiskAreas: ['BKC G-Block Glass High-Rise Boulevard', 'Kalanagar Traffic Interchange', 'Santacruz East Highway Flyovers'],
    lowRiskAreas: ['MMRDA City Park Waterbody', 'Mithi River Greenway'],
  },
  {
    id: 'ward-mum-kw',
    name: 'Ward K/West: Andheri West - Juhu - Versova, Mumbai',
    zone: 'Western Suburbs Transit & Coastal Sector',
    city: 'Mumbai',
    state: 'Maharashtra',
    regionType: 'Maharashtra',
    center: [19.1197, 72.8468],
    bounds: [
      [19.145, 72.818],
      [19.148, 72.865],
      [19.095, 72.868],
      [19.092, 72.822],
      [19.145, 72.818],
    ],
    population: 320000,
    vulnerableCount: 62000,
    treeCanopyPct: 22,
    builtDensityPct: 80,
    vulnerabilityIndex: 68,
    uhiOffsetDegC: 2.3,
    highRiskAreas: ['Andheri West Metro-Local Interchange', 'SV Road Market Bottleneck', 'Lokhandwala Open Car Parks'],
    lowRiskAreas: ['Juhu Beach Coastal Front', 'Versova Mangrove Creek Breeze'],
  },
  {
    id: 'ward-mum-rs',
    name: 'Ward R/South: Kandivali - Borivali West, Mumbai',
    zone: 'North Suburbs Residential Corridor',
    city: 'Mumbai',
    state: 'Maharashtra',
    regionType: 'Maharashtra',
    center: [19.2062, 72.8526],
    bounds: [
      [19.235, 72.830],
      [19.238, 72.875],
      [19.180, 72.878],
      [19.178, 72.835],
      [19.235, 72.830],
    ],
    population: 290000,
    vulnerableCount: 54000,
    treeCanopyPct: 28,
    builtDensityPct: 76,
    vulnerabilityIndex: 59,
    uhiOffsetDegC: 1.9,
    highRiskAreas: ['Kandivali Station Road Bazaar', 'Western Express Highway Tarmac Strip'],
    lowRiskAreas: ['Sanjay Gandhi National Park Buffer', 'Eksar Talav Shaded Walkways'],
  },

  // --- Thane Municipal Corporation (TMC - Maharashtra) ---
  {
    id: 'ward-tha-01',
    name: 'TMC Ward 1: Naupada - Kopri - Thane Station',
    zone: 'Thane Central Urban Core',
    city: 'Thane',
    state: 'Maharashtra',
    regionType: 'Maharashtra',
    center: [19.1860, 72.9759],
    bounds: [
      [19.205, 72.955],
      [19.208, 72.992],
      [19.168, 72.995],
      [19.165, 72.958],
      [19.205, 72.955],
    ],
    population: 220000,
    vulnerableCount: 48000,
    treeCanopyPct: 21,
    builtDensityPct: 84,
    vulnerabilityIndex: 73,
    uhiOffsetDegC: 2.6,
    highRiskAreas: ['Thane Station SATIS Bus Deck', 'Gokhale Road Commercial Market', 'Kopri East Colony'],
    lowRiskAreas: ['Masunda (Talao Pali) Lake Promenade', 'Kopri Creek Shaded Edge'],
  },
  {
    id: 'ward-tha-02',
    name: 'TMC Ward 2: Majiwada - Ghodbunder Road',
    zone: 'Rapid Urbanization High-Rise Spine',
    city: 'Thane',
    state: 'Maharashtra',
    regionType: 'Maharashtra',
    center: [19.2245, 72.9782],
    bounds: [
      [19.255, 72.950],
      [19.258, 72.998],
      [19.205, 72.998],
      [19.202, 72.952],
      [19.255, 72.950],
    ],
    population: 245000,
    vulnerableCount: 39000,
    treeCanopyPct: 26,
    builtDensityPct: 78,
    vulnerabilityIndex: 62,
    uhiOffsetDegC: 2.1,
    highRiskAreas: ['Majiwada Junction Flyover Maze', 'Ghodbunder Concrete Arterial Road', 'Kapurbawdi Naka'],
    lowRiskAreas: ['Yeoor Hills Foothills Forest', 'Upvan Lake Riparian Zone'],
  },

  // --- Navi Mumbai Municipal Corporation (NMMC - Maharashtra) ---
  {
    id: 'ward-nmmc-01',
    name: 'NMMC Ward 1: Vashi - Turbhe MIDC',
    zone: 'Harbour Commercial & Logistics Hub',
    city: 'Navi Mumbai',
    state: 'Maharashtra',
    regionType: 'Maharashtra',
    center: [19.0771, 73.0039],
    bounds: [
      [19.098, 72.985],
      [19.100, 73.025],
      [19.055, 73.028],
      [19.052, 72.988],
      [19.098, 72.985],
    ],
    population: 210000,
    vulnerableCount: 49000,
    treeCanopyPct: 24,
    builtDensityPct: 79,
    vulnerabilityIndex: 69,
    uhiOffsetDegC: 2.4,
    highRiskAreas: ['Turbhe Chemical Industrial Area', 'Vashi APMC Wholesale Market Yards', 'Sion-Panvel Expressway Crossing'],
    lowRiskAreas: ['Vashi Sagar Vihar Waterfront', 'Mini Seashore Shaded Jogging Track'],
  },
  {
    id: 'ward-nmmc-02',
    name: 'NMMC Ward 2: CBD Belapur - Nerul',
    zone: 'Creekside Administrative & Civic Hub',
    city: 'Navi Mumbai',
    state: 'Maharashtra',
    regionType: 'Maharashtra',
    center: [19.0185, 73.0402],
    bounds: [
      [19.045, 73.018],
      [19.048, 73.065],
      [18.995, 73.068],
      [18.992, 73.020],
      [19.045, 73.018],
    ],
    population: 195000,
    vulnerableCount: 32000,
    treeCanopyPct: 34,
    builtDensityPct: 66,
    vulnerabilityIndex: 48,
    uhiOffsetDegC: 1.4,
    highRiskAreas: ['CBD Belapur Station Plaza', 'Palm Beach Road Open Intersection'],
    lowRiskAreas: ['Parsik Hill Reserve Canopy', 'Jewel of Navi Mumbai Waterfront'],
  },

  // --- Nagpur Municipal Corporation (NMC - Vidarbha Heat Belt) ---
  {
    id: 'ward-nag-01',
    name: 'NMC Ward 1: Sitabuldi - Dharampeth, Nagpur',
    zone: 'Nagpur Central Commercial Core',
    city: 'Nagpur',
    state: 'Maharashtra',
    regionType: 'Maharashtra',
    center: [21.1458, 79.0805],
    bounds: [
      [21.165, 79.062],
      [21.168, 79.098],
      [21.128, 79.100],
      [21.125, 79.065],
      [21.165, 79.062],
    ],
    population: 235000,
    vulnerableCount: 56000,
    treeCanopyPct: 22,
    builtDensityPct: 82,
    vulnerabilityIndex: 82,
    uhiOffsetDegC: 3.1,
    highRiskAreas: ['Sitabuldi Main Market Spine', 'Nagpur Central Railway Terminus Forecourt', 'Variety Square Interchange'],
    lowRiskAreas: ['Ambazari Lake Forest Buffer', 'Maharajbagh Zoo Botanical Shading'],
  },
  {
    id: 'ward-nag-02',
    name: 'NMC Ward 2: Lakadganj - Itwari Wholesale Corridor, Nagpur',
    zone: 'East High-Thermal Hotspot',
    city: 'Nagpur',
    state: 'Maharashtra',
    regionType: 'Maharashtra',
    center: [21.1560, 79.1180],
    bounds: [
      [21.175, 79.100],
      [21.178, 79.142],
      [21.135, 79.145],
      [21.132, 79.102],
      [21.175, 79.100],
    ],
    population: 275000,
    vulnerableCount: 78000,
    treeCanopyPct: 12,
    builtDensityPct: 91,
    vulnerabilityIndex: 89,
    uhiOffsetDegC: 3.8,
    highRiskAreas: ['Itwari Grain Market Narrow Lanes', 'Lakadganj Timber Pavements', 'Gandhibagh Wholesale Hub'],
    lowRiskAreas: ['Gandhisagar Lake Perimeter Canopy', 'Reshimbagh Shaded Grounds'],
  },
  {
    id: 'ward-nag-03',
    name: 'NMC Ward 3: Sadar - Civil Lines, Nagpur',
    zone: 'Institutional Green Canopy Zone',
    city: 'Nagpur',
    state: 'Maharashtra',
    regionType: 'Maharashtra',
    center: [21.1685, 79.0712],
    bounds: [
      [21.188, 79.052],
      [21.190, 79.088],
      [21.148, 79.090],
      [21.145, 79.055],
      [21.188, 79.052],
    ],
    population: 145000,
    vulnerableCount: 22000,
    treeCanopyPct: 46,
    builtDensityPct: 54,
    vulnerabilityIndex: 36,
    uhiOffsetDegC: 0.8,
    highRiskAreas: ['Sadar Residency Road Commercial Strip', 'Katol Road Highway Junction'],
    lowRiskAreas: ['Civil Lines Heritage Canopy', 'Seminary Hills Reserve Forest', 'Japanese Garden'],
  },

  // --- Nashik Municipal Corporation (NMC - North Maharashtra) ---
  {
    id: 'ward-nsk-01',
    name: 'NMC Ward 1: Panchavati - Godavari Ghats, Nashik',
    zone: 'Heritage Riverfront & Pilgrim Core',
    city: 'Nashik',
    state: 'Maharashtra',
    regionType: 'Maharashtra',
    center: [20.0059, 73.7997],
    bounds: [
      [20.025, 73.780],
      [20.028, 73.818],
      [19.985, 73.820],
      [19.982, 73.782],
      [20.025, 73.780],
    ],
    population: 198000,
    vulnerableCount: 46000,
    treeCanopyPct: 20,
    builtDensityPct: 83,
    vulnerabilityIndex: 66,
    uhiOffsetDegC: 2.1,
    highRiskAreas: ['Ramkund Concrete Ghats', 'Malegaon Stand Bus Depot', 'Dindori Naka Open Crossing'],
    lowRiskAreas: ['Godavari Shaded Riverbank Promenade', 'Tapovan Forest Ashram'],
  },
  {
    id: 'ward-nsk-02',
    name: 'NMC Ward 2: CIDCO - Ambad Industrial Belt, Nashik',
    zone: 'South-West Manufacturing & Urban Zone',
    city: 'Nashik',
    state: 'Maharashtra',
    regionType: 'Maharashtra',
    center: [19.9572, 73.7431],
    bounds: [
      [19.980, 73.722],
      [19.982, 73.765],
      [19.935, 73.768],
      [19.932, 73.725],
      [19.980, 73.722],
    ],
    population: 230000,
    vulnerableCount: 52000,
    treeCanopyPct: 18,
    builtDensityPct: 82,
    vulnerabilityIndex: 71,
    uhiOffsetDegC: 2.4,
    highRiskAreas: ['MIDC Ambad Factory Corridors', 'Mumbai-Agra Highway Overpass', 'Pawan Nagar Market'],
    lowRiskAreas: ['Pandavleni Shaded Base Garden', 'CIDCO Shambhaji Stadium Grounds'],
  },

  // --- Chhatrapati Sambhaji Nagar (Aurangabad - Marathwada Zone) ---
  {
    id: 'ward-csn-01',
    name: 'CSN Ward 1: Kranti Chowk - Nirala Bazaar, Sambhaji Nagar',
    zone: 'Marathwada Central Commercial Hub',
    city: 'Chhatrapati Sambhaji Nagar',
    state: 'Maharashtra',
    regionType: 'Maharashtra',
    center: [19.8762, 75.3240],
    bounds: [
      [19.898, 75.305],
      [19.900, 75.345],
      [19.855, 75.348],
      [19.852, 75.308],
      [19.898, 75.305],
    ],
    population: 215000,
    vulnerableCount: 51000,
    treeCanopyPct: 16,
    builtDensityPct: 84,
    vulnerabilityIndex: 77,
    uhiOffsetDegC: 2.8,
    highRiskAreas: ['Kranti Chowk Flyover Junction', 'Nirala Bazaar High Density Shopping', 'Shahgunj Wholesale Market'],
    lowRiskAreas: ['Siddharth Garden & Zoo Trees', 'Himayat Bagh Botanical Shading'],
  },
  {
    id: 'ward-csn-02',
    name: 'CSN Ward 2: Chikalthana MIDC - Airport Belt',
    zone: 'East Industrial & Logistics Corridor',
    city: 'Chhatrapati Sambhaji Nagar',
    state: 'Maharashtra',
    regionType: 'Maharashtra',
    center: [19.8785, 75.3850],
    bounds: [
      [19.902, 75.362],
      [19.905, 75.412],
      [19.855, 75.415],
      [19.852, 75.365],
      [19.902, 75.362],
    ],
    population: 180000,
    vulnerableCount: 44000,
    treeCanopyPct: 14,
    builtDensityPct: 85,
    vulnerabilityIndex: 79,
    uhiOffsetDegC: 3.0,
    highRiskAreas: ['MIDC Industrial Heavy Machinery Sheds', 'Jalna Road Tarmac Spine', 'Mundhada Square'],
    lowRiskAreas: ['Airport Perimeter Shaded Buffers', 'Prozone Shaded Promenade'],
  },

  // --- Solapur Municipal Corporation (South Maharashtra Dry Plateau) ---
  {
    id: 'ward-sol-01',
    name: 'SMC Ward 1: Solapur Central - Navi Peth - Sidheshwar',
    zone: 'Dry Plateau Textile & Commercial Core',
    city: 'Solapur',
    state: 'Maharashtra',
    regionType: 'Maharashtra',
    center: [17.6599, 75.9064],
    bounds: [
      [17.685, 75.885],
      [17.688, 75.928],
      [17.635, 75.930],
      [17.632, 75.888],
      [17.685, 75.885],
    ],
    population: 265000,
    vulnerableCount: 71000,
    treeCanopyPct: 14,
    builtDensityPct: 86,
    vulnerabilityIndex: 85,
    uhiOffsetDegC: 3.3,
    highRiskAreas: ['Navi Peth Dense Cloth Market', 'Old Poona Naka Traffic Circle', 'MIDC Chhatrapati Sambhaji Textile Mills'],
    lowRiskAreas: ['Siddheshwar Lake Waterfront', 'Hutatma Smruti Shaded Garden'],
  },

  // --- Kolhapur Municipal Corporation (South-West Maharashtra) ---
  {
    id: 'ward-klp-01',
    name: 'KMC Ward 1: Mahalaxmi - Shahupuri - Station Road, Kolhapur',
    zone: 'Heritage Temple & Agro-Commercial Core',
    city: 'Kolhapur',
    state: 'Maharashtra',
    regionType: 'Maharashtra',
    center: [16.7050, 74.2433],
    bounds: [
      [16.728, 74.225],
      [16.730, 74.265],
      [16.685, 74.268],
      [16.682, 74.228],
      [16.728, 74.225],
    ],
    population: 205000,
    vulnerableCount: 39000,
    treeCanopyPct: 28,
    builtDensityPct: 76,
    vulnerabilityIndex: 56,
    uhiOffsetDegC: 1.6,
    highRiskAreas: ['Mahalaxmi Temple Pilgrim Corridors', 'Shahupuri Jaggery Market', 'Dasara Chowk Open Tarmac'],
    lowRiskAreas: ['Rankala Lake Shaded Promenade', 'New Palace Royal Forest Canopy'],
  },

  // --- Amravati Municipal Corporation (West Vidarbha Heatwave Core) ---
  {
    id: 'ward-amr-01',
    name: 'AMC Ward 1: Rajkamal Chowk - Badnera Road, Amravati',
    zone: 'Vidarbha High-WBGT Industrial & Transit Core',
    city: 'Amravati',
    state: 'Maharashtra',
    regionType: 'Maharashtra',
    center: [20.9320, 77.7523],
    bounds: [
      [20.955, 77.730],
      [20.958, 77.775],
      [20.910, 77.778],
      [20.908, 77.732],
      [20.955, 77.730],
    ],
    population: 225000,
    vulnerableCount: 62000,
    treeCanopyPct: 15,
    builtDensityPct: 86,
    vulnerabilityIndex: 86,
    uhiOffsetDegC: 3.5,
    highRiskAreas: ['Rajkamal Square Open Terminal', 'Cotton Market Wholesale Yards', 'Badnera Rail Junction Transit Deck'],
    lowRiskAreas: ['Chhatri Talao Lake Canopy', 'Wadali Garden Forest Reserve'],
  },
];

// ==============================================================================
// 2. NATIONAL CAPITALS & METROPOLITAN WARDS ACROSS INDIA
// ==============================================================================
export const NATIONAL_WARDS: WardInfo[] = [
  // --- Delhi NCR (National Capital Region) ---
  {
    id: 'ward-del-01',
    name: 'Ward DL-01: Connaught Place - Barakhamba Core, Delhi',
    zone: 'National Capital Central Business District',
    city: 'Delhi NCR',
    state: 'Delhi',
    regionType: 'National',
    center: [28.6304, 77.2177],
    bounds: [
      [28.648, 77.202],
      [28.650, 77.235],
      [28.615, 77.238],
      [28.612, 77.205],
      [28.648, 77.202],
    ],
    population: 175000,
    vulnerableCount: 34000,
    treeCanopyPct: 26,
    builtDensityPct: 84,
    vulnerabilityIndex: 72,
    uhiOffsetDegC: 2.8,
    highRiskAreas: ['Inner Circle CP Radial Roads', 'Barakhamba Road Glass Facade Canyon', 'Shivaji Stadium Bus Terminal'],
    lowRiskAreas: ['Central Park Shaded Lawn', 'Rajpath / Kartavya Path Canopy Corridor'],
  },
  {
    id: 'ward-del-02',
    name: 'Ward DL-02: Chandni Chowk - Kashmere Gate, Delhi',
    zone: 'Historic Walled City High-Density Core',
    city: 'Delhi NCR',
    state: 'Delhi',
    regionType: 'National',
    center: [28.6562, 77.2300],
    bounds: [
      [28.675, 77.215],
      [28.678, 77.248],
      [28.640, 77.250],
      [28.638, 77.218],
      [28.675, 77.215],
    ],
    population: 310000,
    vulnerableCount: 95000,
    treeCanopyPct: 7,
    builtDensityPct: 96,
    vulnerabilityIndex: 93,
    uhiOffsetDegC: 4.1,
    highRiskAreas: ['Khari Baoli Spice Bazaar Pavement', 'Kashmere Gate ISBT Concrete Deck', 'Old Delhi Railway Station Plazas'],
    lowRiskAreas: ['Red Fort Shaded Outer Moat Gardens', 'Qudsia Bagh Heritage Park'],
  },
  {
    id: 'ward-del-03',
    name: 'Ward DL-03: Hauz Khas - Green Park - Saket, Delhi',
    zone: 'South Delhi Institutional & Heritage Green Belt',
    city: 'Delhi NCR',
    state: 'Delhi',
    regionType: 'National',
    center: [28.5494, 77.2001],
    bounds: [
      [28.572, 77.182],
      [28.575, 77.225],
      [28.528, 77.228],
      [28.525, 77.185],
      [28.572, 77.182],
    ],
    population: 240000,
    vulnerableCount: 41000,
    treeCanopyPct: 42,
    builtDensityPct: 65,
    vulnerabilityIndex: 45,
    uhiOffsetDegC: 1.2,
    highRiskAreas: ['AIIMS-Safdarjung Traffic Ring Road', 'Saket District Centre Concrete Plaza'],
    lowRiskAreas: ['Deer Park Lake Reserve', 'Hauz Khas District Forest', 'Sanjay Van Ridge'],
  },
  {
    id: 'ward-del-04',
    name: 'Ward DL-04: Anand Vihar - Laxmi Nagar, Delhi',
    zone: 'East Trans-Yamuna Transit & Commercial Spine',
    city: 'Delhi NCR',
    state: 'Delhi',
    regionType: 'National',
    center: [28.6502, 77.3150],
    bounds: [
      [28.672, 77.295],
      [28.675, 77.338],
      [28.628, 77.340],
      [28.625, 77.298],
      [28.672, 77.295],
    ],
    population: 360000,
    vulnerableCount: 98000,
    treeCanopyPct: 12,
    builtDensityPct: 91,
    vulnerabilityIndex: 89,
    uhiOffsetDegC: 3.7,
    highRiskAreas: ['Anand Vihar ISBT & Railway Terminus', 'Vikas Marg Dense Retail Corridor', 'Ghazipur Border Tarmac'],
    lowRiskAreas: ['Sanjay Lake Shaded Buffer', 'Yamuna Floodplain Green Zone'],
  },
  {
    id: 'ward-del-05',
    name: 'Ward DL-05: Dwarka Sector 10 - IGI Airport Corridor, Delhi',
    zone: 'South-West Planned Sub-City & Aviation Belt',
    city: 'Delhi NCR',
    state: 'Delhi',
    regionType: 'National',
    center: [28.5823, 77.0500],
    bounds: [
      [28.610, 77.025],
      [28.612, 77.078],
      [28.555, 77.080],
      [28.552, 77.028],
      [28.610, 77.025],
    ],
    population: 290000,
    vulnerableCount: 49000,
    treeCanopyPct: 25,
    builtDensityPct: 77,
    vulnerabilityIndex: 64,
    uhiOffsetDegC: 2.2,
    highRiskAreas: ['Dwarka Sector 12 City Centre Concrete Plaza', 'Airport Road Expressway Open Tarmac'],
    lowRiskAreas: ['Dwarka Sector 9 District Park', 'Bharat Vandana Park Woods'],
  },

  // --- Bengaluru (BBMP - Karnataka) ---
  {
    id: 'ward-blr-01',
    name: 'BBMP Ward 1: Majestic - Kempegowda - Shivajinagar, Bengaluru',
    zone: 'Central Transit Interchange & Core Retail',
    city: 'Bengaluru',
    state: 'Karnataka',
    regionType: 'National',
    center: [12.9767, 77.5713],
    bounds: [
      [12.995, 77.555],
      [12.998, 77.592],
      [12.958, 77.595],
      [12.955, 77.558],
      [12.995, 77.555],
    ],
    population: 260000,
    vulnerableCount: 62000,
    treeCanopyPct: 22,
    builtDensityPct: 85,
    vulnerabilityIndex: 72,
    uhiOffsetDegC: 2.3,
    highRiskAreas: ['Majestic BMTC & KSRTC Bus Concourse', 'Chickpet Narrow Wholesale Alleys', 'Shivajinagar Bus Terminal'],
    lowRiskAreas: ['Cubbon Park 300-Acre Tree Canopy', 'Freedom Park Shaded Pavilions'],
  },
  {
    id: 'ward-blr-02',
    name: 'BBMP Ward 2: Koramangala - Indiranagar - MG Road, Bengaluru',
    zone: 'East-Central Commercial & Tech Hub',
    city: 'Bengaluru',
    state: 'Karnataka',
    regionType: 'National',
    center: [12.9352, 77.6245],
    bounds: [
      [12.958, 77.605],
      [12.960, 77.648],
      [12.915, 77.650],
      [12.912, 77.608],
      [12.958, 77.605],
    ],
    population: 225000,
    vulnerableCount: 36000,
    treeCanopyPct: 32,
    builtDensityPct: 76,
    vulnerabilityIndex: 52,
    uhiOffsetDegC: 1.5,
    highRiskAreas: ['Sony World Signal Junction', '100ft Road Retail Concrete Strip', 'Koramangala 80ft Road Flyover'],
    lowRiskAreas: ['Defense Colony Tree-lined Avenues', 'Agara Lake Promenade Canopy'],
  },
  {
    id: 'ward-blr-03',
    name: 'BBMP Ward 3: Whitefield - ITPL Corridor, Bengaluru',
    zone: 'East Tech Parks & Glass High-Rise Spine',
    city: 'Bengaluru',
    state: 'Karnataka',
    regionType: 'National',
    center: [12.9698, 77.7499],
    bounds: [
      [12.995, 77.728],
      [12.998, 77.775],
      [12.945, 77.778],
      [12.942, 77.730],
      [12.995, 77.728],
    ],
    population: 280000,
    vulnerableCount: 45000,
    treeCanopyPct: 18,
    builtDensityPct: 83,
    vulnerabilityIndex: 68,
    uhiOffsetDegC: 2.5,
    highRiskAreas: ['ITPL Main Road Tarmac Canyons', 'Hope Farm Traffic Circle', 'Kundalahalli Gate Underpass'],
    lowRiskAreas: ['Inner Circle Ground Shaded Perimeter', 'Nallurahalli Lake Buffer'],
  },
  {
    id: 'ward-blr-04',
    name: 'BBMP Ward 4: Jayanagar - Basavanagudi, Bengaluru',
    zone: 'South Heritage Canopy & Residential Zone',
    city: 'Bengaluru',
    state: 'Karnataka',
    regionType: 'National',
    center: [12.9308, 77.5838],
    bounds: [
      [12.952, 77.565],
      [12.955, 77.605],
      [12.910, 77.608],
      [12.908, 77.568],
      [12.952, 77.565],
    ],
    population: 195000,
    vulnerableCount: 31000,
    treeCanopyPct: 45,
    builtDensityPct: 62,
    vulnerabilityIndex: 38,
    uhiOffsetDegC: 0.8,
    highRiskAreas: ['Jayanagar 4th Block BDA Complex Open Parking', 'South End Circle Concrete Junction'],
    lowRiskAreas: ['Lalbagh Botanical Garden Shaded Canopy', 'Madhavan Park Tree Groves', 'Bugle Rock Park'],
  },

  // --- Hyderabad (GHMC - Telangana) ---
  {
    id: 'ward-hyd-01',
    name: 'GHMC Ward 1: Charminar - Madina - Laad Bazaar, Hyderabad',
    zone: 'Historic Old City High Thermal Density',
    city: 'Hyderabad',
    state: 'Telangana',
    regionType: 'National',
    center: [17.3616, 78.4747],
    bounds: [
      [17.380, 78.455],
      [17.382, 78.495],
      [17.342, 78.498],
      [17.340, 78.458],
      [17.380, 78.455],
    ],
    population: 320000,
    vulnerableCount: 92000,
    treeCanopyPct: 9,
    builtDensityPct: 93,
    vulnerabilityIndex: 90,
    uhiOffsetDegC: 3.7,
    highRiskAreas: ['Madina Chowk Open Pavement Bazaars', 'Charminar Pedestrian Precinct (High Solar Reflected Heat)', 'Moazzam Jahi Market'],
    lowRiskAreas: ['Nehru Zoological Park Forest Buffer', 'Musi Riverbank Shaded Pockets'],
  },
  {
    id: 'ward-hyd-02',
    name: 'GHMC Ward 2: HITEC City - Madhapur - Gachibowli, Hyderabad',
    zone: 'Cyberabad Tech & Glass Towers Sector',
    city: 'Hyderabad',
    state: 'Telangana',
    regionType: 'National',
    center: [17.4474, 78.3762],
    bounds: [
      [17.472, 78.352],
      [17.475, 78.402],
      [17.422, 78.405],
      [17.420, 78.355],
      [17.472, 78.352],
    ],
    population: 260000,
    vulnerableCount: 38000,
    treeCanopyPct: 22,
    builtDensityPct: 82,
    vulnerabilityIndex: 65,
    uhiOffsetDegC: 2.4,
    highRiskAreas: ['Cyber Towers Roundabout Tarmac', 'Gachibowli Outer Ring Road Interchange', 'Bio-diversity Junction Flyover'],
    lowRiskAreas: ['Kotla Vijayabhaskara Reddy Botanical Garden', 'Durgam Cheruvu Lakefront Breezeway'],
  },
  {
    id: 'ward-hyd-03',
    name: 'GHMC Ward 3: Secunderabad Station - Begumpet, Hyderabad',
    zone: 'Cantonment & North Rail Transit Hub',
    city: 'Hyderabad',
    state: 'Telangana',
    regionType: 'National',
    center: [17.4399, 78.4983],
    bounds: [
      [17.462, 78.475],
      [17.465, 78.522],
      [17.418, 78.525],
      [17.415, 78.478],
      [17.462, 78.475],
    ],
    population: 230000,
    vulnerableCount: 51000,
    treeCanopyPct: 32,
    builtDensityPct: 75,
    vulnerabilityIndex: 62,
    uhiOffsetDegC: 1.9,
    highRiskAreas: ['Secunderabad Station Forecourt', 'Paradise Circle Highway Junction', 'MG Road Commercial Spine'],
    lowRiskAreas: ['Hussain Sagar Lakefront Promenade (Tank Bund)', 'Sanjeevaiah Park Lake Shading'],
  },

  // --- Ahmedabad (AMC - Gujarat) ---
  {
    id: 'ward-ahd-01',
    name: 'AMC Ward 1: Relief Road - Lal Darwaja - Kalupur, Ahmedabad',
    zone: 'Walled City Extreme Solar Heat Island',
    city: 'Ahmedabad',
    state: 'Gujarat',
    regionType: 'National',
    center: [23.0276, 72.5873],
    bounds: [
      [23.048, 72.568],
      [23.050, 72.608],
      [23.008, 72.610],
      [23.005, 72.570],
      [23.048, 72.568],
    ],
    population: 340000,
    vulnerableCount: 104000,
    treeCanopyPct: 8,
    builtDensityPct: 94,
    vulnerabilityIndex: 92,
    uhiOffsetDegC: 3.9,
    highRiskAreas: ['Kalupur Railway Station Plaza', 'Lal Darwaja City Bus Terminus', 'Manek Chowk Pavement Corridor'],
    lowRiskAreas: ['Sabarmati Riverfront Promenade Lower Walkway', 'Kankaria Lake Shaded Circular Walk'],
  },
  {
    id: 'ward-ahd-02',
    name: 'AMC Ward 2: SG Highway - Bodakdev - Vastrapur, Ahmedabad',
    zone: 'West New Urban Expansion & Commercial Zone',
    city: 'Ahmedabad',
    state: 'Gujarat',
    regionType: 'National',
    center: [23.0401, 72.5186],
    bounds: [
      [23.065, 72.495],
      [23.068, 72.545],
      [23.018, 72.548],
      [23.015, 72.498],
      [23.065, 72.495],
    ],
    population: 270000,
    vulnerableCount: 46000,
    treeCanopyPct: 22,
    builtDensityPct: 81,
    vulnerabilityIndex: 67,
    uhiOffsetDegC: 2.6,
    highRiskAreas: ['SG Highway Open Multi-lane Tarmac', 'Iskcon Flyover Underbridge Crossings', 'Judges Bungalow Road Paved Corridor'],
    lowRiskAreas: ['Vastrapur Lake Shaded Gardens', 'Gujarat University Canopy Campus'],
  },

  // --- Chennai (GCC - Tamil Nadu - Coastal Humid Heat) ---
  {
    id: 'ward-chn-01',
    name: 'GCC Ward 1: George Town - Chennai Central - Parrys',
    zone: 'North Commercial Port & Transit Hub',
    city: 'Chennai',
    state: 'Tamil Nadu',
    regionType: 'National',
    center: [13.0878, 80.2838],
    bounds: [
      [13.110, 80.265],
      [13.112, 80.302],
      [13.068, 80.305],
      [13.065, 80.268],
      [13.110, 80.265],
    ],
    population: 290000,
    vulnerableCount: 82000,
    treeCanopyPct: 10,
    builtDensityPct: 92,
    vulnerabilityIndex: 87,
    uhiOffsetDegC: 3.2,
    highRiskAreas: ['Chennai Central Station Forecourt', 'Parrys Corner Bus Terminus', 'NSC Bose Road Wholesale Wholesale Spine'],
    lowRiskAreas: ['Marina Beach Sea Breeze Front', 'Fort St. George Shaded Grounds'],
  },
  {
    id: 'ward-chn-02',
    name: 'GCC Ward 2: T. Nagar - Panagal Park - Mylapore, Chennai',
    zone: 'Central Retail & Heritage Cultural Core',
    city: 'Chennai',
    state: 'Tamil Nadu',
    regionType: 'National',
    center: [13.0418, 80.2341],
    bounds: [
      [13.062, 80.215],
      [13.065, 80.255],
      [13.020, 80.258],
      [13.018, 80.218],
      [13.062, 80.215],
    ],
    population: 310000,
    vulnerableCount: 74000,
    treeCanopyPct: 18,
    builtDensityPct: 86,
    vulnerabilityIndex: 78,
    uhiOffsetDegC: 2.8,
    highRiskAreas: ['Ranganathan Street Dense Pedestrian Canyon', 'Panagal Park Commercial Ring', 'Mylapore Tank Open Pavements'],
    lowRiskAreas: ['Semmozhi Poonga Botanical Garden Canopy', 'Theosophical Society Shaded Woods'],
  },
  {
    id: 'ward-chn-03',
    name: 'GCC Ward 3: OMR Tech Corridor - Guindy, Chennai',
    zone: 'Industrial & IT Expressway Belt',
    city: 'Chennai',
    state: 'Tamil Nadu',
    regionType: 'National',
    center: [12.9780, 80.2450],
    bounds: [
      [13.005, 80.218],
      [13.008, 80.272],
      [12.952, 80.275],
      [12.950, 80.220],
      [13.005, 80.218],
    ],
    population: 260000,
    vulnerableCount: 42000,
    treeCanopyPct: 28,
    builtDensityPct: 78,
    vulnerabilityIndex: 63,
    uhiOffsetDegC: 2.1,
    highRiskAreas: ['OMR Tidel Park Highway Crossing', 'Guindy Industrial Estate Sheds', 'Velachery Main Road Open Overpass'],
    lowRiskAreas: ['Guindy National Park Forest Canopy', 'IIT Madras Shaded Woodland Reserve'],
  },

  // --- Kolkata (KMC - West Bengal - Gangetic Delta) ---
  {
    id: 'ward-kol-01',
    name: 'KMC Ward 1: BBD Bagh - Esplanade - Burrabazar, Kolkata',
    zone: 'Historic Riverfront Financial & Trading Core',
    city: 'Kolkata',
    state: 'West Bengal',
    regionType: 'National',
    center: [22.5726, 88.3500],
    bounds: [
      [22.592, 88.332],
      [22.595, 88.368],
      [22.552, 88.370],
      [22.550, 88.335],
      [22.592, 88.332],
    ],
    population: 310000,
    vulnerableCount: 88000,
    treeCanopyPct: 14,
    builtDensityPct: 91,
    vulnerabilityIndex: 86,
    uhiOffsetDegC: 3.3,
    highRiskAreas: ['Howrah Bridge Approach & Bus Terminus', 'Burrabazar Wholesale Dense Alleys', 'Esplanade Tram & Bus Interchange'],
    lowRiskAreas: ['Maidan Shaded Expanses', 'Eden Gardens Park Trees', 'Millennium Park Hooghly Waterfront'],
  },
  {
    id: 'ward-kol-02',
    name: 'KMC Ward 2: Salt Lake Sector V - New Town, Kolkata',
    zone: 'Planned IT Hub & Modern Commercial Sector',
    city: 'Kolkata',
    state: 'West Bengal',
    regionType: 'National',
    center: [22.5802, 88.4350],
    bounds: [
      [22.605, 88.412],
      [22.608, 88.460],
      [22.558, 88.462],
      [22.555, 88.415],
      [22.605, 88.412],
    ],
    population: 240000,
    vulnerableCount: 38000,
    treeCanopyPct: 24,
    builtDensityPct: 79,
    vulnerabilityIndex: 61,
    uhiOffsetDegC: 2.2,
    highRiskAreas: ['Sector V Ring Road Glass Corridors', 'Karunamoyee Central Bus Stand', 'Major Arterial Road Open Pavement'],
    lowRiskAreas: ['Central Park Salt Lake Lake & Forest', 'Eco Park Shaded Island Sanctuary'],
  },

  // --- Jaipur (JMC - Rajasthan - Arid Heat & High Solar Radiation) ---
  {
    id: 'ward-jpr-01',
    name: 'JMC Ward 1: Johari Bazaar - Hawa Mahal - Walled City, Jaipur',
    zone: 'Pink City Historic Walled Thermal Core',
    city: 'Jaipur',
    state: 'Rajasthan',
    regionType: 'National',
    center: [26.9239, 75.8267],
    bounds: [
      [26.945, 75.808],
      [26.948, 75.845],
      [26.902, 75.848],
      [26.900, 75.810],
      [26.945, 75.808],
    ],
    population: 285000,
    vulnerableCount: 84000,
    treeCanopyPct: 9,
    builtDensityPct: 92,
    vulnerabilityIndex: 91,
    uhiOffsetDegC: 3.8,
    highRiskAreas: ['Tripolia Bazaar Narrow Commercial Corridor', 'Badi Chaupar Open Concrete Square', 'Ajmeri Gate Traffic Hub'],
    lowRiskAreas: ['Ram Niwas Bagh Tree Canopy', 'Central Museum Shaded Grounds'],
  },
  {
    id: 'ward-jpr-02',
    name: 'JMC Ward 2: Mansarovar - Tonk Road, Jaipur',
    zone: 'South Commercial & Transit Axis',
    city: 'Jaipur',
    state: 'Rajasthan',
    regionType: 'National',
    center: [26.8520, 75.7680],
    bounds: [
      [26.878, 75.745],
      [26.880, 75.792],
      [26.828, 75.795],
      [26.825, 75.748],
      [26.878, 75.745],
    ],
    population: 260000,
    vulnerableCount: 52000,
    treeCanopyPct: 18,
    builtDensityPct: 83,
    vulnerabilityIndex: 73,
    uhiOffsetDegC: 2.7,
    highRiskAreas: ['Tonk Road Gopalpura Flyover Junction', 'Mansarovar Metro Terminal Forecourt', 'B2 Bypass Open Intersection'],
    lowRiskAreas: ['City Park Mansarovar Woodlands', 'Jawahar Circle Rose Garden & Canopy'],
  },

  // --- Lucknow (LMC - Uttar Pradesh - Indo-Gangetic Plain) ---
  {
    id: 'ward-lko-01',
    name: 'LMC Ward 1: Hazratganj - Charbagh Railway Junction, Lucknow',
    zone: 'Historic Administrative & Rail Transit Spine',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    regionType: 'National',
    center: [26.8467, 80.9462],
    bounds: [
      [26.868, 80.925],
      [26.870, 80.968],
      [26.825, 80.970],
      [26.822, 80.928],
      [26.868, 80.925],
    ],
    population: 295000,
    vulnerableCount: 76000,
    treeCanopyPct: 19,
    builtDensityPct: 84,
    vulnerabilityIndex: 81,
    uhiOffsetDegC: 3.1,
    highRiskAreas: ['Charbagh Station Main Exit Plaza', 'Hazratganj Main Retail Pavements', 'Vidhan Sabha Marg Open Corridor'],
    lowRiskAreas: ['Lucknow Zoo & Botanical Garden Canopy', 'Gomti Riverfront Shaded Walkway'],
  },
];

// ==============================================================================
// 3. COMBINED COMPREHENSIVE NATIONAL & MAHARASHTRA DATASET
// ==============================================================================
export const ALL_REGIONAL_WARDS: WardInfo[] = [
  ...MAHARASHTRA_WARDS,
  ...NATIONAL_WARDS,
];

// Backward compatibility: export PUNE_WARDS representing Pune urban wards
export const PUNE_WARDS: WardInfo[] = ALL_REGIONAL_WARDS.filter(
  (w) => w.city === 'Pune' || w.name.includes('Pune')
);

/**
 * Resolve any lat/lng coordinate across India to the nearest or enclosing administrative ward.
 */
export function resolveWardByCoords(lat: number, lng: number): WardInfo {
  // 1. Check exact polygon enclosure across regional wards with proximity sanity check
  for (const ward of ALL_REGIONAL_WARDS) {
    const distCenter = calculateDistanceKm(lat, lng, ward.center[0], ward.center[1]);
    if (distCenter <= 45 && pointInPolygon([lat, lng], ward.bounds)) {
      return ward;
    }
  }

  // 2. Fallback to nearest ward center
  let nearestWard = ALL_REGIONAL_WARDS[0];
  let minDistance = calculateDistanceKm(lat, lng, nearestWard.center[0], nearestWard.center[1]);

  for (let i = 1; i < ALL_REGIONAL_WARDS.length; i++) {
    const d = calculateDistanceKm(lat, lng, ALL_REGIONAL_WARDS[i].center[0], ALL_REGIONAL_WARDS[i].center[1]);
    if (d < minDistance) {
      minDistance = d;
      nearestWard = ALL_REGIONAL_WARDS[i];
    }
  }

  return nearestWard;
}

// ==============================================================================
// 4. PROTECTION NETWORK (Cooling Centers, Hydration Kiosks, Shaded Pavilions)
// ==============================================================================
export const PROTECTION_POINTS: ProtectionPoint[] = [
  // --- Pune Municipal Corporation ---
  {
    id: 'prot-w1',
    name: 'PMC Smart Chilled Water Kiosk - Sambhaji Park',
    type: 'water',
    categoryLabel: 'Drinking Water Kiosk',
    lat: 18.5285,
    lng: 73.8465,
    address: 'JM Road, Near Sambhaji Garden Gate 1, Shivajinagar, Pune',
    wardId: 'ward-14',
    zone: 'Central Pune Zone',
    status: 'Available',
    capacity: 2500,
    currentOccupancy: 840,
    availableCapacity: 1660,
    amenities: ['RO Purified Chilled Water', 'Free ORS Pouches', 'Bottle Refill Sensor', 'Shaded Alcove'],
    operatingHours: '24 Hours',
    isEmergencyReady: true,
  },
  {
    id: 'prot-c1',
    name: 'Shivajinagar Municipal Climate Cooling Centre',
    type: 'cooling',
    categoryLabel: 'Air-Conditioned Cooling Shelter',
    lat: 18.5332,
    lng: 73.8421,
    address: 'Ghole Road Civic Center Ground Floor, Shivajinagar, Pune',
    wardId: 'ward-14',
    zone: 'Central Pune Zone',
    status: 'Available',
    capacity: 180,
    currentOccupancy: 72,
    availableCapacity: 108,
    amenities: ['AC Rest Lounge (24°C)', 'Misting Station', 'Emergency Paramedic Station', 'Free Electrolyte Drinks', 'Phone Charging'],
    operatingHours: '09:00 AM - 08:00 PM',
    isEmergencyReady: true,
    contact: '+91 20 2550 1200',
  },
  {
    id: 'prot-s1',
    name: 'Chhatrapati Sambhaji Park Canopy Rest Zone',
    type: 'shade',
    categoryLabel: 'Canopied Shade & Rest Area',
    lat: 18.5269,
    lng: 73.8458,
    address: 'Jangali Maharaj Road, Deccan Gymkhana, Pune',
    wardId: 'ward-14',
    zone: 'Central Pune Zone',
    status: 'Available',
    capacity: 450,
    currentOccupancy: 190,
    availableCapacity: 260,
    amenities: ['Dense Tree Canopy (4.2°C Cooler)', 'Benches with Mist Fans', 'Drinking Water Taps', 'Security Attendants'],
    operatingHours: '06:00 AM - 09:00 PM',
  },
  {
    id: 'prot-h1',
    name: 'Sassoon General Hospital - Emergency Heat Stroke Unit',
    type: 'healthcare',
    categoryLabel: 'Emergency Trauma & Heat Center',
    lat: 18.5262,
    lng: 73.8741,
    address: 'Station Road, Near Pune Railway Station, Pune',
    wardId: 'ward-14',
    zone: 'Central Pune Zone',
    status: 'Available',
    capacity: 35,
    currentOccupancy: 12,
    availableCapacity: 23,
    amenities: ['Dedicated Ice-Bath Resuscitation Units', '24x7 Critical Care ICU', 'Cold Saline Infusions', 'Free Emergency Treatment'],
    operatingHours: '24 Hours Open',
    isEmergencyReady: true,
    contact: '+91 20 2612 8000',
  },
  {
    id: 'prot-w2',
    name: 'Mandai Market Municipal Hydration Point',
    type: 'water',
    categoryLabel: 'Drinking Water Kiosk',
    lat: 18.5134,
    lng: 73.8561,
    address: 'Mahatma Phule Mandai Outer Gate, Kasba Peth, Pune',
    wardId: 'ward-21',
    zone: 'Heritage Core Zone',
    status: 'Limited',
    capacity: 3000,
    currentOccupancy: 2450,
    availableCapacity: 550,
    amenities: ['Chilled Filtered Water', 'Free ORS Salt', 'Wheelchair Friendly'],
    operatingHours: '06:00 AM - 10:00 PM',
  },
  {
    id: 'prot-c2',
    name: 'Vishrambaug Wada Heritage Climate Relief Hall',
    type: 'cooling',
    categoryLabel: 'Public Cooling Centre',
    lat: 18.5146,
    lng: 73.8532,
    address: 'Bajirao Road, Sadashiv Peth, Pune',
    wardId: 'ward-21',
    zone: 'Heritage Core Zone',
    status: 'Available',
    capacity: 120,
    currentOccupancy: 58,
    availableCapacity: 62,
    amenities: ['Air Conditioned Hall', 'Cool Drinking Water', 'Medical First Aid Kit', 'Resting Recliners'],
    operatingHours: '10:00 AM - 07:00 PM',
    isEmergencyReady: true,
  },
  {
    id: 'prot-w3',
    name: 'Karve Road Metro Station Hydration Hub',
    type: 'water',
    categoryLabel: 'Drinking Water Kiosk',
    lat: 18.5065,
    lng: 73.8192,
    address: 'Karve Road Metro Entry Gate, Kothrud, Pune',
    wardId: 'ward-09',
    zone: 'West Hills Zone',
    status: 'Available',
    capacity: 2000,
    currentOccupancy: 610,
    availableCapacity: 1390,
    amenities: ['Chilled RO Water', 'Touchless Dispenser', 'Shaded Shelter'],
    operatingHours: '24 Hours',
  },
  {
    id: 'prot-s2',
    name: 'Sarasbaug Sacred Grove & Lake Promenade',
    type: 'shade',
    categoryLabel: 'Canopied Shade & Rest Area',
    lat: 18.5005,
    lng: 73.8542,
    address: 'Swargate - Parvati Road, Pune',
    wardId: 'ward-25',
    zone: 'South Transit Zone',
    status: 'Available',
    capacity: 600,
    currentOccupancy: 210,
    availableCapacity: 390,
    amenities: ['Microclimate Waterfront Cooling (-3°C)', 'Centuries-old Tree Shading', 'Misting Canopy'],
    operatingHours: '05:30 AM - 09:30 PM',
  },
  {
    id: 'prot-c3',
    name: 'Swargate Transit Passenger Cooling Pod',
    type: 'cooling',
    categoryLabel: 'Air-Conditioned Transit Cooling',
    lat: 18.5022,
    lng: 73.8584,
    address: 'Swargate ST Stand Main Concourse, Pune',
    wardId: 'ward-25',
    zone: 'South Transit Zone',
    status: 'Limited',
    capacity: 150,
    currentOccupancy: 122,
    availableCapacity: 28,
    amenities: ['High-Power Air Cooling', 'Instant Rehydration Salts', 'Emergency Nurse on Duty'],
    operatingHours: '24 Hours',
    isEmergencyReady: true,
  },
  {
    id: 'prot-c5',
    name: 'Hadapsar Gadital Transit AC Cooling Hub',
    type: 'cooling',
    categoryLabel: 'Air-Conditioned Cooling Shelter',
    lat: 18.4998,
    lng: 73.9312,
    address: 'Solapur Road, Gadital Terminal, Hadapsar, Pune',
    wardId: 'ward-18',
    zone: 'East Industrial & Logistics Zone',
    status: 'Limited',
    capacity: 160,
    currentOccupancy: 138,
    availableCapacity: 22,
    amenities: ['Industrial Air Cooling', 'Drinking Water Dispensers', 'First Aid Station'],
    operatingHours: '24 Hours',
    isEmergencyReady: true,
  },

  // --- Mumbai (BMC / MCGM) ---
  {
    id: 'prot-mum-1',
    name: 'CST Railway Concourse Emergency Climate Shelter',
    type: 'cooling',
    categoryLabel: 'High-Capacity Transit Cooling',
    lat: 18.9400,
    lng: 72.8353,
    address: 'Chhatrapati Shivaji Maharaj Terminus (CSMT), Fort, Mumbai',
    wardId: 'ward-mum-a',
    zone: 'South Mumbai Coastal Financial Core',
    status: 'Available',
    capacity: 350,
    currentOccupancy: 140,
    availableCapacity: 210,
    amenities: ['Industrial Chilled Air', 'Cold Water Kiosks', 'ORS Dispensing', 'Stretcher Access'],
    operatingHours: '24 Hours',
    isEmergencyReady: true,
  },
  {
    id: 'prot-mum-2',
    name: 'BMC Pyaau Hydration Hub - Crawford Market',
    type: 'water',
    categoryLabel: 'Drinking Water Kiosk',
    lat: 18.9472,
    lng: 72.8335,
    address: 'Dr. D.N. Road, Near Crawford Market Outer Gate, Mumbai',
    wardId: 'ward-mum-c',
    zone: 'Historic Dense Commercial Zone',
    status: 'Available',
    capacity: 4000,
    currentOccupancy: 1200,
    availableCapacity: 2800,
    amenities: ['Chilled Mineral Water', 'Automatic Bottle Refill', 'Shaded Rest Benches'],
    operatingHours: '24 Hours',
    isEmergencyReady: true,
  },
  {
    id: 'prot-mum-3',
    name: 'Dharavi Transit Climate Care Pavilion',
    type: 'cooling',
    categoryLabel: 'Community Cooling Center',
    lat: 19.0435,
    lng: 72.8520,
    address: '90-Feet Road Civic Community Hall, Dharavi, Mumbai',
    wardId: 'ward-mum-gn',
    zone: 'Central High-Vulnerability Microclimate',
    status: 'Available',
    capacity: 220,
    currentOccupancy: 95,
    availableCapacity: 125,
    amenities: ['High-Velocity Mist Cooling', 'Emergency First Aid Station', 'Electrolyte Packs', 'Women & Child Rest Area'],
    operatingHours: '08:00 AM - 08:00 PM',
    isEmergencyReady: true,
  },
  {
    id: 'prot-mum-4',
    name: 'BKC Shaded Green Promenade & Water Point',
    type: 'shade',
    categoryLabel: 'Canopied Shade & Rest Area',
    lat: 19.0672,
    lng: 72.8690,
    address: 'G-Block Avenue 3, Bandra Kurla Complex, Mumbai',
    wardId: 'ward-mum-he',
    zone: 'Financial District & Transit Core',
    status: 'Available',
    capacity: 500,
    currentOccupancy: 160,
    availableCapacity: 340,
    amenities: ['Misting Pergolas', 'Clean Drinking Water', 'Seating Benches'],
    operatingHours: '06:00 AM - 10:00 PM',
  },

  // --- Nagpur (NMC) ---
  {
    id: 'prot-nag-1',
    name: 'NMC Extreme Heat Shelter - Sitabuldi Interchange',
    type: 'cooling',
    categoryLabel: 'Air-Conditioned Cooling Shelter',
    lat: 21.1472,
    lng: 79.0830,
    address: 'Sitabuldi Metro Station Ground concourse, Nagpur',
    wardId: 'ward-nag-01',
    zone: 'Nagpur Central Commercial Core',
    status: 'Available',
    capacity: 300,
    currentOccupancy: 110,
    availableCapacity: 190,
    amenities: ['AC Rest Hall', 'High-Output Cold Water Dispenser', 'Emergency Ice Sponge Packs', 'Doctor on Call'],
    operatingHours: '24 Hours',
    isEmergencyReady: true,
  },
  {
    id: 'prot-nag-2',
    name: 'Itwari Wholesale Hydration Station',
    type: 'water',
    categoryLabel: 'Drinking Water Kiosk',
    lat: 21.1575,
    lng: 79.1195,
    address: 'Main Grain Market Chowk, Itwari, Nagpur',
    wardId: 'ward-nag-02',
    zone: 'East High-Thermal Hotspot',
    status: 'Available',
    capacity: 3500,
    currentOccupancy: 1800,
    availableCapacity: 1700,
    amenities: ['Chilled RO Water Kiosks', 'Electrolyte Salts', 'Mist Fans'],
    operatingHours: '08:00 AM - 09:00 PM',
  },

  // --- Nashik (NMC) ---
  {
    id: 'prot-nsk-1',
    name: 'Panchavati Godavari Pilgrim Cooling Shelter',
    type: 'cooling',
    categoryLabel: 'Public Cooling Centre',
    lat: 20.0072,
    lng: 73.8015,
    address: 'Near Ramkund Main Gate, Panchavati, Nashik',
    wardId: 'ward-nsk-01',
    zone: 'Heritage Riverfront & Pilgrim Core',
    status: 'Available',
    capacity: 250,
    currentOccupancy: 80,
    availableCapacity: 170,
    amenities: ['Air Cooled Hall', 'Cold Potable Water', 'Medical First Aid'],
    operatingHours: '06:00 AM - 10:00 PM',
    isEmergencyReady: true,
  },

  // --- Delhi NCR ---
  {
    id: 'prot-del-1',
    name: 'Delhi DDMA Emergency Climate Shelter - Connaught Place',
    type: 'cooling',
    categoryLabel: 'Air-Conditioned Cooling Shelter',
    lat: 28.6315,
    lng: 77.2185,
    address: 'Palika Kendra Underground Concourse, Connaught Place, New Delhi',
    wardId: 'ward-del-01',
    zone: 'National Capital Central Business District',
    status: 'Available',
    capacity: 400,
    currentOccupancy: 150,
    availableCapacity: 250,
    amenities: ['Air Conditioned Hall (22°C)', 'Cold Drinking Water Fountains', 'ORS Envelopes', 'Paramedic Nurse'],
    operatingHours: '24 Hours',
    isEmergencyReady: true,
  },
  {
    id: 'prot-del-2',
    name: 'Kashmere Gate ISBT Climate Rest Pod',
    type: 'cooling',
    categoryLabel: 'High-Capacity Transit Cooling',
    lat: 28.6672,
    lng: 77.2285,
    address: 'Maharana Pratap ISBT Main Departure Concourse, Kashmere Gate, Delhi',
    wardId: 'ward-del-02',
    zone: 'Historic Walled City High-Density Core',
    status: 'Available',
    capacity: 350,
    currentOccupancy: 210,
    availableCapacity: 140,
    amenities: ['High-Power Industrial AC', 'Chilled Water Dispensers', 'Stretcher Beds', 'Electrolyte Packs'],
    operatingHours: '24 Hours',
    isEmergencyReady: true,
  },

  // --- Bengaluru ---
  {
    id: 'prot-blr-1',
    name: 'Majestic Transit Hydration & Cooling Point',
    type: 'water',
    categoryLabel: 'Drinking Water Kiosk',
    lat: 12.9775,
    lng: 77.5725,
    address: 'Kempegowda Bus Station Platform 1 Forecourt, Majestic, Bengaluru',
    wardId: 'ward-blr-01',
    zone: 'Central Transit Interchange & Core Retail',
    status: 'Available',
    capacity: 3500,
    currentOccupancy: 1200,
    availableCapacity: 2300,
    amenities: ['RO Purified Cold Water', 'ORS Powder', 'Canopy Shading'],
    operatingHours: '24 Hours',
    isEmergencyReady: true,
  },
];

// ==============================================================================
// 5. HEALTHCARE INSTITUTIONS & HEAT STROKE EMERGENCY CENTERS
// ==============================================================================
export const HEALTHCARE_FACILITIES: HealthcareFacility[] = [
  // --- Pune Hospitals ---
  {
    id: 'hosp-1',
    name: 'Sassoon General Hospital & BJ Medical College',
    type: 'Emergency Care',
    lat: 18.5262,
    lng: 73.8741,
    distanceKm: 2.4,
    travelTimeMins: 8,
    travelMode: 'Driving',
    address: 'Station Road, Near Pune Junction Railway Station, Pune',
    wardId: 'ward-14',
    phone: '+91 20 2612 8000',
    isOpen24x7: true,
    status: 'Available',
    emergencyIndicator: true,
    heatStrokeBedsAvailable: 14,
    totalHeatBeds: 20,
    directionsUrl: 'https://maps.google.com/?q=18.5262,73.8741',
    dataSource: 'LIVE',
  },
  {
    id: 'hosp-2',
    name: 'KEM Hospital & Research Centre Pune',
    type: 'Hospital',
    lat: 18.5192,
    lng: 73.8698,
    distanceKm: 2.1,
    travelTimeMins: 7,
    travelMode: 'Driving',
    address: 'Rasta Peth, Sardar Moodliar Road, Pune',
    wardId: 'ward-21',
    phone: '+91 20 6603 7300',
    isOpen24x7: true,
    status: 'Available',
    emergencyIndicator: true,
    heatStrokeBedsAvailable: 8,
    totalHeatBeds: 12,
    directionsUrl: 'https://maps.google.com/?q=18.5192,73.8698',
    dataSource: 'LIVE',
  },
  {
    id: 'hosp-3',
    name: 'Poona Hospital & Research Centre',
    type: 'Hospital',
    lat: 18.5115,
    lng: 73.8441,
    distanceKm: 1.6,
    travelTimeMins: 6,
    travelMode: 'Driving',
    address: 'Near Alka Talkies Chowk, Sadashiv Peth, Pune',
    wardId: 'ward-14',
    phone: '+91 20 6609 6000',
    isOpen24x7: true,
    status: 'Available',
    emergencyIndicator: true,
    heatStrokeBedsAvailable: 6,
    totalHeatBeds: 10,
    directionsUrl: 'https://maps.google.com/?q=18.5115,73.8441',
    dataSource: 'CURATED',
  },
  {
    id: 'hosp-4',
    name: 'Deenanath Mangeshkar Hospital & Research Center',
    type: 'Emergency Care',
    lat: 18.5008,
    lng: 73.8312,
    distanceKm: 3.1,
    travelTimeMins: 11,
    travelMode: 'Driving',
    address: 'Erandwane, Near Mhatre Bridge, Pune',
    wardId: 'ward-09',
    phone: '+91 20 4015 1000',
    isOpen24x7: true,
    status: 'Available',
    emergencyIndicator: true,
    heatStrokeBedsAvailable: 11,
    totalHeatBeds: 16,
    directionsUrl: 'https://maps.google.com/?q=18.5008,73.8312',
    dataSource: 'LIVE',
  },
  {
    id: 'hosp-5',
    name: 'Pune District Hospital, Aundh',
    type: 'Hospital',
    lat: 18.5632,
    lng: 73.8105,
    distanceKm: 4.8,
    travelTimeMins: 14,
    travelMode: 'Driving',
    address: 'Aundh Camp, Old Sangvi Road, Pune',
    wardId: 'ward-07',
    phone: '+91 20 2728 0134',
    isOpen24x7: true,
    status: 'Available',
    emergencyIndicator: true,
    heatStrokeBedsAvailable: 9,
    totalHeatBeds: 15,
    directionsUrl: 'https://maps.google.com/?q=18.5632,73.8105',
    dataSource: 'CURATED',
  },

  // --- Mumbai Hospitals ---
  {
    id: 'hosp-mum-1',
    name: 'KEM Hospital & Seth GS Medical College, Mumbai',
    type: 'Emergency Care',
    lat: 19.0028,
    lng: 72.8424,
    distanceKm: 3.2,
    travelTimeMins: 10,
    travelMode: 'Driving',
    address: 'Acharya Donde Marg, Parel, Mumbai, Maharashtra 400012',
    wardId: 'ward-mum-gs',
    phone: '+91 22 2410 7000',
    isOpen24x7: true,
    status: 'Available',
    emergencyIndicator: true,
    heatStrokeBedsAvailable: 18,
    totalHeatBeds: 28,
    directionsUrl: 'https://maps.google.com/?q=19.0028,72.8424',
    dataSource: 'LIVE',
  },
  {
    id: 'hosp-mum-2',
    name: 'Grant Govt Medical College & Sir JJ Group of Hospitals, Mumbai',
    type: 'Emergency Care',
    lat: 18.9616,
    lng: 72.8340,
    distanceKm: 2.8,
    travelTimeMins: 9,
    travelMode: 'Driving',
    address: 'JJ Hospital Compound, Byculla, Mumbai 400008',
    wardId: 'ward-mum-c',
    phone: '+91 22 2373 5555',
    isOpen24x7: true,
    status: 'Available',
    emergencyIndicator: true,
    heatStrokeBedsAvailable: 22,
    totalHeatBeds: 32,
    directionsUrl: 'https://maps.google.com/?q=18.9616,72.8340',
    dataSource: 'LIVE',
  },
  {
    id: 'hosp-mum-3',
    name: 'Lilavati Hospital & Research Centre Bandra',
    type: 'Hospital',
    lat: 19.0518,
    lng: 72.8290,
    distanceKm: 3.6,
    travelTimeMins: 12,
    travelMode: 'Driving',
    address: 'A-791, Bandra Reclamation, Bandra West, Mumbai 400050',
    wardId: 'ward-mum-he',
    phone: '+91 22 2675 1000',
    isOpen24x7: true,
    status: 'Available',
    emergencyIndicator: true,
    heatStrokeBedsAvailable: 10,
    totalHeatBeds: 15,
    directionsUrl: 'https://maps.google.com/?q=19.0518,72.8290',
    dataSource: 'LIVE',
  },

  // --- Nagpur Hospitals ---
  {
    id: 'hosp-nag-1',
    name: 'Government Medical College & Hospital (GMC) Nagpur',
    type: 'Emergency Care',
    lat: 21.1345,
    lng: 79.0985,
    distanceKm: 2.5,
    travelTimeMins: 8,
    travelMode: 'Driving',
    address: 'Medical Square, Hanuman Nagar, Nagpur, Maharashtra 440003',
    wardId: 'ward-nag-01',
    phone: '+91 712 274 4440',
    isOpen24x7: true,
    status: 'Available',
    emergencyIndicator: true,
    heatStrokeBedsAvailable: 26,
    totalHeatBeds: 36,
    directionsUrl: 'https://maps.google.com/?q=21.1345,79.0985',
    dataSource: 'LIVE',
  },

  // --- Delhi Hospitals ---
  {
    id: 'hosp-del-1',
    name: 'All India Institute of Medical Sciences (AIIMS) New Delhi',
    type: 'Emergency Care',
    lat: 28.5672,
    lng: 77.2100,
    distanceKm: 4.1,
    travelTimeMins: 12,
    travelMode: 'Driving',
    address: 'Sri Aurobindo Marg, Ansari Nagar, New Delhi 110029',
    wardId: 'ward-del-03',
    phone: '+91 11 2658 8500',
    isOpen24x7: true,
    status: 'Available',
    emergencyIndicator: true,
    heatStrokeBedsAvailable: 30,
    totalHeatBeds: 45,
    directionsUrl: 'https://maps.google.com/?q=28.5672,77.2100',
    dataSource: 'LIVE',
  },
  {
    id: 'hosp-del-2',
    name: 'Safdarjung Hospital Emergency Medicine & Burn Care',
    type: 'Emergency Care',
    lat: 28.5705,
    lng: 77.2072,
    distanceKm: 3.9,
    travelTimeMins: 11,
    travelMode: 'Driving',
    address: 'Ring Road, Opposite AIIMS, New Delhi 110029',
    wardId: 'ward-del-03',
    phone: '+91 11 2616 5060',
    isOpen24x7: true,
    status: 'Available',
    emergencyIndicator: true,
    heatStrokeBedsAvailable: 24,
    totalHeatBeds: 35,
    directionsUrl: 'https://maps.google.com/?q=28.5705,77.2072',
    dataSource: 'LIVE',
  },
];

// ==============================================================================
// 6. REGIONAL LANDMARKS FOR SAFE ROUTES
// ==============================================================================
export const REGIONAL_LANDMARKS = [
  // Pune
  { name: 'Shivajinagar Bus Station', lat: 18.5322, lng: 73.8504, city: 'Pune', zone: 'Central' },
  { name: 'FC Road (Goodluck Chowk)', lat: 18.5186, lng: 73.8415, city: 'Pune', zone: 'Central' },
  { name: 'Mahatma Phule Mandai', lat: 18.5134, lng: 73.8561, city: 'Pune', zone: 'Heritage Core' },
  { name: 'Shaniwar Wada Palace', lat: 18.5196, lng: 73.8553, city: 'Pune', zone: 'Heritage Core' },
  { name: 'Pune Railway Junction', lat: 18.5284, lng: 73.8743, city: 'Pune', zone: 'Central/Cantonment' },
  { name: 'Swargate ST Terminal', lat: 18.5022, lng: 73.8584, city: 'Pune', zone: 'South' },
  { name: 'Kothrud Karve Statue', lat: 18.5065, lng: 73.8192, city: 'Pune', zone: 'West' },
  { name: 'Magarpatta Cybercity', lat: 18.5167, lng: 73.9312, city: 'Pune', zone: 'East' },
  { name: 'Phoenix Marketcity Viman Nagar', lat: 18.5621, lng: 73.9168, city: 'Pune', zone: 'North-East' },

  // Mumbai
  { name: 'Chhatrapati Shivaji Maharaj Terminus (CSMT)', lat: 18.9400, lng: 72.8353, city: 'Mumbai', zone: 'South' },
  { name: 'Gateway of India, Colaba', lat: 18.9220, lng: 72.8347, city: 'Mumbai', zone: 'South Coastal' },
  { name: 'Nariman Point Financial District', lat: 18.9256, lng: 72.8242, city: 'Mumbai', zone: 'South' },
  { name: 'Bandra Kurla Complex (BKC)', lat: 18.0664, lng: 72.8682, city: 'Mumbai', zone: 'Central Financial' },
  { name: 'Dadar Station Interchange', lat: 19.0178, lng: 72.8478, city: 'Mumbai', zone: 'Central' },
  { name: 'Andheri Metro Interchange', lat: 19.1197, lng: 72.8468, city: 'Mumbai', zone: 'Western Suburbs' },

  // Nagpur
  { name: 'Nagpur Central Railway Junction', lat: 21.1524, lng: 79.0888, city: 'Nagpur', zone: 'Central' },
  { name: 'Sitabuldi Interchange', lat: 21.1458, lng: 79.0805, city: 'Nagpur', zone: 'Central' },
  { name: 'Zero Mile Stone, Nagpur', lat: 21.1485, lng: 79.0825, city: 'Nagpur', zone: 'Central Landmark' },

  // Nashik
  { name: 'Panchavati Godavari Ghats', lat: 20.0059, lng: 73.7997, city: 'Nashik', zone: 'Heritage Riverfront' },
  { name: 'Nashik CBS Central Bus Station', lat: 19.9975, lng: 73.7898, city: 'Nashik', zone: 'Central' },

  // Delhi NCR
  { name: 'Connaught Place (Rajiv Chowk)', lat: 28.6328, lng: 77.2197, city: 'Delhi NCR', zone: 'Central' },
  { name: 'Kashmere Gate ISBT', lat: 28.6672, lng: 77.2285, city: 'Delhi NCR', zone: 'North Transit' },
  { name: 'India Gate / Kartavya Path', lat: 28.6129, lng: 77.2295, city: 'Delhi NCR', zone: 'Central National' },
  { name: 'AIIMS Medical Square Delhi', lat: 28.5672, lng: 77.2100, city: 'Delhi NCR', zone: 'South' },

  // Bengaluru
  { name: 'Majestic Kempegowda Bus Station', lat: 12.9767, lng: 77.5713, city: 'Bengaluru', zone: 'Central' },
  { name: 'MG Road Metro Station', lat: 12.9756, lng: 77.6067, city: 'Bengaluru', zone: 'Central' },
  { name: 'Whitefield ITPL Gate', lat: 12.9698, lng: 77.7499, city: 'Bengaluru', zone: 'East Tech' },
];

// Backward compatibility
export const PUNE_LANDMARKS = REGIONAL_LANDMARKS.filter((l) => l.city === 'Pune');
