import { WardInfo, ProtectionPoint, HealthcareFacility } from './types.js';

// Haversine formula to compute great-circle distance in kilometers
export function calculateDistanceKm(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 6371; // Earth's radius in km
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLon = ((lon2 - lon1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLon / 2) *
      Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return Math.round(R * c * 10) / 10;
}

// Ray-casting point in polygon
export function pointInPolygon(point: [number, number], vs: [number, number][]): boolean {
  const x = point[0];
  const y = point[1];
  let inside = false;
  for (let i = 0, j = vs.length - 1; i < vs.length; j = i++) {
    const xi = vs[i][0];
    const yi = vs[i][1];
    const xj = vs[j][0];
    const yj = vs[j][1];
    const intersect = yi > y !== yj > y && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi;
    if (intersect) inside = !inside;
  }
  return inside;
}

// Key Pune administrative wards with spatial boundaries and urban vulnerability factors
export const PUNE_WARDS: WardInfo[] = [
  {
    id: 'ward-14',
    name: 'Ward 14: Shivajinagar - Ghole Road',
    zone: 'Central Pune Zone',
    center: [18.5314, 73.8446],
    bounds: [
      [18.542, 73.834],
      [18.545, 73.856],
      [18.524, 73.861],
      [18.518, 73.839],
      [18.542, 73.834],
    ],
    population: 142000,
    vulnerableCount: 28400,
    treeCanopyPct: 32,
    builtDensityPct: 68,
    vulnerabilityIndex: 58,
    uhiOffsetDegC: 1.8,
    highRiskAreas: ['FC Road Shopping Spine', 'Shivajinagar Bus & Railway Terminus', 'Modern College Square'],
    lowRiskAreas: ['Sambhaji Park Canopy', 'Agricultural College Green Belt', 'Mutha River Greenway'],
  },
  {
    id: 'ward-21',
    name: 'Ward 21: Kasba Peth - Vishrambaug Wada',
    zone: 'Heritage Core Zone',
    center: [18.5178, 73.8582],
    bounds: [
      [18.526, 73.851],
      [18.528, 73.866],
      [18.511, 73.869],
      [18.508, 73.852],
      [18.526, 73.851],
    ],
    population: 178000,
    vulnerableCount: 46200,
    treeCanopyPct: 11,
    builtDensityPct: 89,
    vulnerabilityIndex: 84,
    uhiOffsetDegC: 3.2,
    highRiskAreas: ['Mandai Wholesale Bazaar', 'Laxmi Road Dense Corridor', 'Phadke Haud Transit'],
    lowRiskAreas: ['Shaniwar Wada Shaded Lawns', 'PMC Saraswati High School Covered Quad'],
  },
  {
    id: 'ward-09',
    name: 'Ward 9: Kothrud - Bavdhan',
    zone: 'West Hills Zone',
    center: [18.5074, 73.8077],
    bounds: [
      [18.521, 73.792],
      [18.523, 73.821],
      [18.491, 73.818],
      [18.489, 73.791],
      [18.521, 73.792],
    ],
    population: 195000,
    vulnerableCount: 31000,
    treeCanopyPct: 44,
    builtDensityPct: 56,
    vulnerabilityIndex: 38,
    uhiOffsetDegC: 0.9,
    highRiskAreas: ['Karve Statue Highway Crossing', 'Chandani Chowk Flyover Junction'],
    lowRiskAreas: ['ARAI Vetal Tekdi Reserve', 'Kothrud Hillside Shaded Parks', 'MIT Garden'],
  },
  {
    id: 'ward-07',
    name: 'Ward 7: Aundh - Baner',
    zone: 'North-West Tech Zone',
    center: [18.558, 73.807],
    bounds: [
      [18.575, 73.792],
      [18.577, 73.824],
      [18.541, 73.828],
      [18.542, 73.794],
      [18.575, 73.792],
    ],
    population: 165000,
    vulnerableCount: 24700,
    treeCanopyPct: 36,
    builtDensityPct: 62,
    vulnerabilityIndex: 42,
    uhiOffsetDegC: 1.2,
    highRiskAreas: ['Baner High Street Open Plaza', 'Aundh ITI Uncovered Intersection'],
    lowRiskAreas: ['Pashan Lake Riparian Buffer', 'University of Pune Shaded Woods', 'Sindh Society Canopy'],
  },
  {
    id: 'ward-18',
    name: 'Ward 18: Hadapsar - Mundhwa',
    zone: 'East Industrial & Logistics Zone',
    center: [18.502, 73.927],
    bounds: [
      [18.524, 73.905],
      [18.528, 73.952],
      [18.481, 73.955],
      [18.479, 73.907],
      [18.524, 73.905],
    ],
    population: 230000,
    vulnerableCount: 57500,
    treeCanopyPct: 16,
    builtDensityPct: 82,
    vulnerabilityIndex: 76,
    uhiOffsetDegC: 2.7,
    highRiskAreas: ['Gadital Bustling Interchange', 'Magarpatta South Outer Ring', 'Industrial Metal Yards'],
    lowRiskAreas: ['Amanora Shaded Park Perimeter', 'Gliding Centre Buffer Zone'],
  },
  {
    id: 'ward-12',
    name: 'Ward 12: Viman Nagar - Nagar Road',
    zone: 'North-East Airport Zone',
    center: [18.567, 73.914],
    bounds: [
      [18.584, 73.896],
      [18.586, 73.935],
      [18.552, 73.938],
      [18.551, 73.898],
      [18.584, 73.896],
    ],
    population: 154000,
    vulnerableCount: 26000,
    treeCanopyPct: 25,
    builtDensityPct: 75,
    vulnerabilityIndex: 61,
    uhiOffsetDegC: 2.1,
    highRiskAreas: ['Pune-Ahmednagar Highway Tarmac', 'Phoenix Mall Transit Drop-off'],
    lowRiskAreas: ['Joggers Park Viman Nagar', 'Symbiosis Campus Shaded Walkways'],
  },
  {
    id: 'ward-25',
    name: 'Ward 25: Swargate - Parvati',
    zone: 'South Transit Zone',
    center: [18.498, 73.856],
    bounds: [
      [18.511, 73.847],
      [18.513, 73.868],
      [18.484, 73.869],
      [18.482, 73.848],
      [18.511, 73.847],
    ],
    population: 188000,
    vulnerableCount: 48800,
    treeCanopyPct: 22,
    builtDensityPct: 78,
    vulnerabilityIndex: 72,
    uhiOffsetDegC: 2.4,
    highRiskAreas: ['Swargate ST Bus Terminal Square', 'Jedhe Chowk Flyover Underdeck'],
    lowRiskAreas: ['Parvati Hill Forest Reserve', 'Sarasbaug Shaded Lake Complex'],
  },
];

export function resolveWardByCoords(lat: number, lng: number): WardInfo {
  // Check exact polygon enclosure
  for (const ward of PUNE_WARDS) {
    if (pointInPolygon([lat, lng], ward.bounds)) {
      return ward;
    }
  }

  // Fallback to nearest ward center
  let nearestWard = PUNE_WARDS[0];
  let minDistance = calculateDistanceKm(lat, lng, nearestWard.center[0], nearestWard.center[1]);

  for (let i = 1; i < PUNE_WARDS.length; i++) {
    const d = calculateDistanceKm(lat, lng, PUNE_WARDS[i].center[0], PUNE_WARDS[i].center[1]);
    if (d < minDistance) {
      minDistance = d;
      nearestWard = PUNE_WARDS[i];
    }
  }

  return nearestWard;
}

// Municipal & community protection network
export const PROTECTION_POINTS: ProtectionPoint[] = [
  {
    id: 'prot-w1',
    name: 'PMC Smart Chilled Water Kiosk - Sambhaji Park',
    type: 'water',
    categoryLabel: 'Drinking Water Kiosk',
    lat: 18.5285,
    lng: 73.8465,
    address: 'JM Road, Near Sambhaji Garden Gate 1, Shivajinagar',
    wardId: 'ward-14',
    zone: 'Central Pune Zone',
    status: 'Available',
    capacity: 2500,
    currentOccupancy: 840,
    availableCapacity: 1660,
    amenities: ['RO Purified Chilled Water', 'Free ORS Pouches', 'Bottle Refill Sensor', 'Shaded Alcove'],
    operatingHours: '24 Hours',
    isEmergencyReady: true,
  },
  {
    id: 'prot-c1',
    name: 'Shivajinagar Municipal Climate Cooling Centre',
    type: 'cooling',
    categoryLabel: 'Air-Conditioned Cooling Shelter',
    lat: 18.5332,
    lng: 73.8421,
    address: 'Ghole Road Civic Center Ground Floor, Shivajinagar',
    wardId: 'ward-14',
    zone: 'Central Pune Zone',
    status: 'Available',
    capacity: 180,
    currentOccupancy: 72,
    availableCapacity: 108,
    amenities: ['AC Rest Lounge (24°C)', 'Misting Station', 'Emergency Paramedic Station', 'Free Electrolyte Drinks', 'Phone Charging'],
    operatingHours: '09:00 AM - 08:00 PM',
    isEmergencyReady: true,
    contact: '+91 20 2550 1200',
  },
  {
    id: 'prot-s1',
    name: 'Chhatrapati Sambhaji Park Canopy Rest Zone',
    type: 'shade',
    categoryLabel: 'Canopied Shade & Rest Area',
    lat: 18.5269,
    lng: 73.8458,
    address: 'Jangali Maharaj Road, Deccan Gymkhana',
    wardId: 'ward-14',
    zone: 'Central Pune Zone',
    status: 'Available',
    capacity: 450,
    currentOccupancy: 190,
    availableCapacity: 260,
    amenities: ['Dense Tree Canopy (4.2°C Cooler)', 'Benches with Mist Fans', 'Drinking Water Taps', 'Security Attendants'],
    operatingHours: '06:00 AM - 09:00 PM',
  },
  {
    id: 'prot-h1',
    name: 'Sassoon General Hospital - Emergency Heat Stroke Unit',
    type: 'healthcare',
    categoryLabel: 'Emergency Trauma & Heat Center',
    lat: 18.5262,
    lng: 73.8741,
    address: 'Station Road, Near Pune Railway Station',
    wardId: 'ward-14',
    zone: 'Central Pune Zone',
    status: 'Available',
    capacity: 35,
    currentOccupancy: 12,
    availableCapacity: 23,
    amenities: ['Dedicated Ice-Bath Resuscitation Units', '24x7 Critical Care ICU', 'Cold Saline Infusions', 'Free Emergency Treatment'],
    operatingHours: '24 Hours Open',
    isEmergencyReady: true,
    contact: '+91 20 2612 8000',
  },
  {
    id: 'prot-w2',
    name: 'Mandai Market Municipal Hydration Point',
    type: 'water',
    categoryLabel: 'Drinking Water Kiosk',
    lat: 18.5134,
    lng: 73.8561,
    address: 'Mahatma Phule Mandai Outer Gate, Kasba Peth',
    wardId: 'ward-21',
    zone: 'Heritage Core Zone',
    status: 'Limited',
    capacity: 3000,
    currentOccupancy: 2450,
    availableCapacity: 550,
    amenities: ['Chilled Filtered Water', 'Free ORS Salt', 'Wheelchair Friendly'],
    operatingHours: '06:00 AM - 10:00 PM',
  },
  {
    id: 'prot-c2',
    name: 'Vishrambaug Wada Heritage Climate Relief Hall',
    type: 'cooling',
    categoryLabel: 'Public Cooling Centre',
    lat: 18.5146,
    lng: 73.8532,
    address: 'Bajirao Road, Sadashiv Peth',
    wardId: 'ward-21',
    zone: 'Heritage Core Zone',
    status: 'Available',
    capacity: 120,
    currentOccupancy: 58,
    availableCapacity: 62,
    amenities: ['Air Conditioned Hall', 'Cool Drinking Water', 'Medical First Aid Kit', 'Resting Recliners'],
    operatingHours: '10:00 AM - 07:00 PM',
    isEmergencyReady: true,
  },
  {
    id: 'prot-w3',
    name: 'Karve Road Metro Station Hydration Hub',
    type: 'water',
    categoryLabel: 'Drinking Water Kiosk',
    lat: 18.5065,
    lng: 73.8192,
    address: 'Karve Road Metro Entry Gate, Kothrud',
    wardId: 'ward-09',
    zone: 'West Hills Zone',
    status: 'Available',
    capacity: 2000,
    currentOccupancy: 610,
    availableCapacity: 1390,
    amenities: ['Chilled RO Water', 'Touchless Dispenser', 'Shaded Shelter'],
    operatingHours: '24 Hours',
  },
  {
    id: 'prot-s2',
    name: 'Sarasbaug Sacred Grove & Lake Promenade',
    type: 'shade',
    categoryLabel: 'Canopied Shade & Rest Area',
    lat: 18.5005,
    lng: 73.8542,
    address: 'Swargate - Parvati Road',
    wardId: 'ward-25',
    zone: 'South Transit Zone',
    status: 'Available',
    capacity: 600,
    currentOccupancy: 210,
    availableCapacity: 390,
    amenities: ['Microclimate Waterfront Cooling (-3°C)', 'Centuries-old Tree Shading', 'Misting Canopy'],
    operatingHours: '05:30 AM - 09:30 PM',
  },
  {
    id: 'prot-c3',
    name: 'Swargate Transit Passenger Cooling Pod',
    type: 'cooling',
    categoryLabel: 'Air-Conditioned Transit Cooling',
    lat: 18.5022,
    lng: 73.8584,
    address: 'Swargate ST Stand Main Concourse',
    wardId: 'ward-25',
    zone: 'South Transit Zone',
    status: 'Limited',
    capacity: 150,
    currentOccupancy: 122,
    availableCapacity: 28,
    amenities: ['High-Power Air Cooling', 'Instant Rehydration Salts', 'Emergency Nurse on Duty'],
    operatingHours: '24 Hours',
    isEmergencyReady: true,
  },
  {
    id: 'prot-h2',
    name: 'PMC Urban Primary Health Centre (UPHC) Ghole Road',
    type: 'healthcare',
    categoryLabel: 'Primary Health Center',
    lat: 18.5309,
    lng: 73.8471,
    address: 'Off FC Road, Shivajinagar',
    wardId: 'ward-14',
    zone: 'Central Pune Zone',
    status: 'Available',
    capacity: 20,
    currentOccupancy: 8,
    availableCapacity: 12,
    amenities: ['Heat Exhaustion Care', 'Oral & IV Rehydration', 'Vital Signs Monitoring'],
    operatingHours: '08:00 AM - 08:00 PM',
    isEmergencyReady: true,
    contact: '+91 20 2553 4511',
  },
  {
    id: 'prot-c4',
    name: 'Aundh Community Climate Shelter - Ward Office',
    type: 'cooling',
    categoryLabel: 'Public Cooling Centre',
    lat: 18.5594,
    lng: 73.8052,
    address: 'Parihar Chowk, Aundh Ward Office',
    wardId: 'ward-07',
    zone: 'North-West Tech Zone',
    status: 'Available',
    capacity: 140,
    currentOccupancy: 45,
    availableCapacity: 95,
    amenities: ['Air Conditioned', 'Free Water', 'Paramedic Assistance'],
    operatingHours: '09:00 AM - 07:00 PM',
  },
  {
    id: 'prot-w4',
    name: 'Baner Smart City Water Fountain & Shade Shelter',
    type: 'water',
    categoryLabel: 'Drinking Water Kiosk',
    lat: 18.5562,
    lng: 73.7912,
    address: 'Baner Road, Near High Street Circle',
    wardId: 'ward-07',
    zone: 'North-West Tech Zone',
    status: 'Available',
    capacity: 1800,
    currentOccupancy: 490,
    availableCapacity: 1310,
    amenities: ['UV Filtered Water', 'Solar-powered Chillers'],
    operatingHours: '24 Hours',
  },
  {
    id: 'prot-s3',
    name: 'Empress Botanical Garden Shade Corridor',
    type: 'shade',
    categoryLabel: 'Dense Botanic Canopy',
    lat: 18.5081,
    lng: 73.8968,
    address: 'Near Race Course, Camp / Hadapsar Border',
    wardId: 'ward-18',
    zone: 'East Industrial & Logistics Zone',
    status: 'Available',
    capacity: 800,
    currentOccupancy: 220,
    availableCapacity: 580,
    amenities: ['Century Trees with 80% Canopy Shade', 'Perimeter Mist Sprinklers', 'Chilled Water Fountains'],
    operatingHours: '09:00 AM - 06:30 PM',
  },
  {
    id: 'prot-c5',
    name: 'Hadapsar Gadital Transit AC Cooling Hub',
    type: 'cooling',
    categoryLabel: 'Air-Conditioned Cooling Shelter',
    lat: 18.4998,
    lng: 73.9312,
    address: 'Solapur Road, Gadital Terminal, Hadapsar',
    wardId: 'ward-18',
    zone: 'East Industrial & Logistics Zone',
    status: 'Limited',
    capacity: 160,
    currentOccupancy: 138,
    availableCapacity: 22,
    amenities: ['Industrial Air Cooling', 'Drinking Water Dispensers', 'First Aid Station'],
    operatingHours: '24 Hours',
    isEmergencyReady: true,
  }
];

// Verified healthcare & heat-stroke emergency institutions
export const HEALTHCARE_FACILITIES: HealthcareFacility[] = [
  {
    id: 'hosp-1',
    name: 'Sassoon General Hospital & BJ Medical College',
    type: 'Emergency Care',
    lat: 18.5262,
    lng: 73.8741,
    distanceKm: 2.4,
    travelTimeMins: 8,
    travelMode: 'Driving',
    address: 'Station Road, Near Pune Junction Railway Station',
    wardId: 'ward-14',
    phone: '+91 20 2612 8000',
    isOpen24x7: true,
    status: 'Available',
    emergencyIndicator: true,
    heatStrokeBedsAvailable: 14,
    totalHeatBeds: 20,
    directionsUrl: 'https://maps.google.com/?q=18.5262,73.8741',
    dataSource: 'LIVE',
  },
  {
    id: 'hosp-2',
    name: 'KEM Hospital & Research Centre',
    type: 'Hospital',
    lat: 18.5192,
    lng: 73.8698,
    distanceKm: 2.1,
    travelTimeMins: 7,
    travelMode: 'Driving',
    address: 'Rasta Peth, Sardar Moodliar Road, Pune',
    wardId: 'ward-21',
    phone: '+91 20 6603 7300',
    isOpen24x7: true,
    status: 'Available',
    emergencyIndicator: true,
    heatStrokeBedsAvailable: 8,
    totalHeatBeds: 12,
    directionsUrl: 'https://maps.google.com/?q=18.5192,73.8698',
    dataSource: 'LIVE',
  },
  {
    id: 'hosp-3',
    name: 'Poona Hospital & Research Centre',
    type: 'Hospital',
    lat: 18.5115,
    lng: 73.8441,
    distanceKm: 1.6,
    travelTimeMins: 6,
    travelMode: 'Driving',
    address: 'Near Alka Talkies Chowk, Sadashiv Peth',
    wardId: 'ward-14',
    phone: '+91 20 6609 6000',
    isOpen24x7: true,
    status: 'Available',
    emergencyIndicator: true,
    heatStrokeBedsAvailable: 6,
    totalHeatBeds: 10,
    directionsUrl: 'https://maps.google.com/?q=18.5115,73.8441',
    dataSource: 'CURATED',
  },
  {
    id: 'hosp-4',
    name: 'Deenanath Mangeshkar Hospital & Research Center',
    type: 'Emergency Care',
    lat: 18.5008,
    lng: 73.8312,
    distanceKm: 3.1,
    travelTimeMins: 11,
    travelMode: 'Driving',
    address: 'Erandwane, Near Mhatre Bridge, Pune',
    wardId: 'ward-09',
    phone: '+91 20 4015 1000',
    isOpen24x7: true,
    status: 'Available',
    emergencyIndicator: true,
    heatStrokeBedsAvailable: 11,
    totalHeatBeds: 16,
    directionsUrl: 'https://maps.google.com/?q=18.5008,73.8312',
    dataSource: 'LIVE',
  },
  {
    id: 'hosp-5',
    name: 'Pune District Hospital, Aundh',
    type: 'Hospital',
    lat: 18.5632,
    lng: 73.8105,
    distanceKm: 4.8,
    travelTimeMins: 14,
    travelMode: 'Driving',
    address: 'Aundh Camp, Old Sangvi Road, Pune',
    wardId: 'ward-07',
    phone: '+91 20 2728 0134',
    isOpen24x7: true,
    status: 'Available',
    emergencyIndicator: true,
    heatStrokeBedsAvailable: 9,
    totalHeatBeds: 15,
    directionsUrl: 'https://maps.google.com/?q=18.5632,73.8105',
    dataSource: 'CURATED',
  },
  {
    id: 'hosp-6',
    name: 'PMC Urban Primary Health Centre (UPHC) Ghole Road',
    type: 'Urban Clinic',
    lat: 18.5309,
    lng: 73.8471,
    distanceKm: 0.4,
    travelTimeMins: 5,
    travelMode: 'Walking',
    address: 'Ghole Road, Shivajinagar Ward Office Campus',
    wardId: 'ward-14',
    phone: '+91 20 2553 4511',
    isOpen24x7: false,
    status: 'Available',
    emergencyIndicator: false,
    heatStrokeBedsAvailable: 4,
    totalHeatBeds: 6,
    directionsUrl: 'https://maps.google.com/?q=18.5309,73.8471',
    dataSource: 'LIVE',
  },
  {
    id: 'hosp-7',
    name: 'Sahyadri Super Speciality Hospital Deccan',
    type: 'Hospital',
    lat: 18.5142,
    lng: 73.8384,
    distanceKm: 1.2,
    travelTimeMins: 5,
    travelMode: 'Driving',
    address: 'Plot No. 30 C, Erandvane, Karve Road, Deccan',
    wardId: 'ward-14',
    phone: '+91 20 6721 3000',
    isOpen24x7: true,
    status: 'Available',
    emergencyIndicator: true,
    heatStrokeBedsAvailable: 5,
    totalHeatBeds: 8,
    directionsUrl: 'https://maps.google.com/?q=18.5142,73.8384',
    dataSource: 'ESTIMATED',
  },
  {
    id: 'hosp-8',
    name: 'Nobel Hospital & Critical Care Centre Hadapsar',
    type: 'Hospital',
    lat: 18.5041,
    lng: 73.9298,
    distanceKm: 8.5,
    travelTimeMins: 22,
    travelMode: 'Driving',
    address: '169, Magarpatta City Road, Hadapsar',
    wardId: 'ward-18',
    phone: '+91 20 6628 5000',
    isOpen24x7: true,
    status: 'Available',
    emergencyIndicator: true,
    heatStrokeBedsAvailable: 7,
    totalHeatBeds: 12,
    directionsUrl: 'https://maps.google.com/?q=18.5041,73.9298',
    dataSource: 'CURATED',
  }
];

// Curated Pune transit landmarks for the Safe Route origin/destination chooser
export const PUNE_LANDMARKS = [
  { name: 'Shivajinagar Bus Station', lat: 18.5322, lng: 73.8504, zone: 'Central' },
  { name: 'FC Road (Goodluck Chowk)', lat: 18.5186, lng: 73.8415, zone: 'Central' },
  { name: 'Mahatma Phule Mandai', lat: 18.5134, lng: 73.8561, zone: 'Heritage Core' },
  { name: 'Shaniwar Wada Palace', lat: 18.5196, lng: 73.8553, zone: 'Heritage Core' },
  { name: 'Pune Railway Junction', lat: 18.5284, lng: 73.8743, zone: 'Central/Cantonment' },
  { name: 'Sarasbaug Lake Gardens', lat: 18.5005, lng: 73.8542, zone: 'South' },
  { name: 'Swargate ST Terminal', lat: 18.5022, lng: 73.8584, zone: 'South' },
  { name: 'Savitribai Phule Pune University', lat: 18.5529, lng: 73.8248, zone: 'North-West' },
  { name: 'Parihar Chowk Aundh', lat: 18.5594, lng: 73.8052, zone: 'North-West' },
  { name: 'Kothrud Karve Statue', lat: 18.5065, lng: 73.8192, zone: 'West' },
  { name: 'Magarpatta Cybercity', lat: 18.5167, lng: 73.9312, zone: 'East' },
  { name: 'Phoenix Marketcity Viman Nagar', lat: 18.5621, lng: 73.9168, zone: 'North-East' }
];
